### ISSUE TITLE
Cleanup of the problems found by `lint`.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4536]
### Description
We have already over 1000 `lint` warnings. After a change to `webpack` + `babel` we have to filter `lint` messages to find errors.

### What we have to do
- [x] as @wszymanski [mentioned](/handsontable/handsontable/pull/4724#pullrequestreview-89749164) in point no. 3, we should replace `0, 1, 2` with `off, warn, error` [source](https://eslint.org/docs/user-guide/configuring),
- [x] `arrow-parens` [source](https://eslint.org/docs/rules/arrow-parens),
- [x] `class-methods-use-this` [source](https://eslint.org/docs/rules/class-methods-use-this),
- [x] `comma-dangle` [source](https://eslint.org/docs/rules/comma-dangle),
- [x] `consistent-return` [source](https://eslint.org/docs/rules/consistent-return),
- [x] `eqeqeq` [source](https://eslint.org/docs/rules/eqeqeq),
- [x] `func-names` [source](https://eslint.org/docs/rules/func-names),
- [x] `import/no-unresolved` + `import/extensions`,
- [x] `linebreak-style` [source](https://eslint.org/docs/rules/linebreak-style),
- [x] `max-dept` [source](https://eslint.org/docs/rules/max-depth),
- [x] `newline-per-chained-call` [source](https://eslint.org/docs/rules/newline-per-chained-call),
- [x] `no-console` [source](https://eslint.org/docs/rules/no-console),
- [x] `no-constant-condition` [source](https://eslint.org/docs/rules/no-constant-condition),
- [x] `no-eq-null` [source](https://eslint.org/docs/rules/no-eq-null),
- [x] `no-extra-semi` [source](https://eslint.org/docs/rules/no-extra-semi),
- [x] `no-param-reassign` [source](https://eslint.org/docs/rules/no-param-reassign),
- [x] `no-plusplus` [source](https://eslint.org/docs/rules/no-plusplus),
- [x] `no-restricted-properties` [source](https://eslint.org/docs/rules/no-restricted-properties),
- [x] `no-restricted-syntax` [source](https://eslint.org/docs/rules/no-restricted-syntax),
- [x] `no-shadow` [source](https://eslint.org/docs/rules/no-shadow),
- [x] `no-undef` [source](https://eslint.org/docs/rules/no-undef),
- [x] `no-undefined` [source](https://eslint.org/docs/rules/no-undefined),
- [x] `no-underscore-dangle` [source](https://eslint.org/docs/rules/no-underscore-dangle),
- [x] `no-unneeded-ternary` [source](https://eslint.org/docs/rules/no-unneeded-ternary),
- [x] `no-unused-vars` [source](https://eslint.org/docs/rules/no-unused-vars),
- [x] `no-use-before-define` [source](https://eslint.org/docs/rules/no-use-before-define),
- [x] `no-var` [source](https://eslint.org/docs/rules/no-var),
- [x] `no-void` [source](https://eslint.org/docs/rules/no-void),
- [x] `object-curly-spacing` [source](https://eslint.org/docs/rules/object-curly-spacing),
- [x] `object-shorthand` [source](https://eslint.org/docs/rules/object-shorthand),
- [x] `one-var` [source](https://eslint.org/docs/rules/one-var),
- [x] `padded-blocks` [source](https://eslint.org/docs/rules/padded-blocks),
- [x] `prefer-arrow-callback` [source](https://eslint.org/docs/rules/prefer-arrow-callback),
- [x] `prefer-const` [source](https://eslint.org/docs/rules/prefer-const),
- [x] `prefer-template` [source](https://eslint.org/docs/rules/prefer-template),
- [x] `prefer-rest-params` [source](https://eslint.org/docs/rules/prefer-rest-params),
- [x] `prefer-spread` [source](https://eslint.org/docs/rules/prefer-spread),
- [x] `space-before-function-paren` [source](https://eslint.org/docs/rules/space-before-function-paren),
- [x] `vars-on-top` [source](https://eslint.org/docs/rules/vars-on-top),

### Rules to be discussed

Let me know if you think that we should discuss some others eslint rules.

### Steps to reproduce
1. Clone repository and go into the target directory.
2. Run `npm i`
3. Run `npm run lint`

### Your environment
* Handsontable version: 0.32.0+
* Browser Name and version: n/a
* Operating System: any

**Comment by wszymanski** [comment]
I updated [comment](https://github.com/handsontable/handsontable/pull/4724#pullrequestreview-89749164) to be more clear. I think 2 more things should be performed.
