### ISSUE TITLE
CopyPaste plugin should support `text/html` data type

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4931]
### Description
We would like to add support for `text/html` data type in CopyPaste plugin.
Next version of this plugin should add these functionalities: 
- [x] copy values as `text/html` (except IE`*`) and `text/plain`
- [x] parse pasted values from `text/html` (except IE`*`) and `text/plain`

What should be additionally resolved:
- [x] #5392 - Can't use Ctrl + C to copy row/col which has first cell is read only
- [x] #5330 - [4.0.0+] Cursor moves to another line on cell edit - Excel copy/paste
- [x] #5300 - [0.34.5+] Paste of row does not work after multiple clicks on target row header cell
- [x] #5277 - Copy Paste from Excel Multi Rows not working 5.0.0 (Community Edition)
- ~[ ] #5254 - Ctrl-C is unstable on IE11~ unconfirmed bug
- [x] #5176 - Crl + C on Row not working on Google Chrome
- [x] #5121 - don't paste from excel to handsontable on mac safari browser
- ~[ ] #5061 - Pasting data that creates new rows may copy a new content to read only cell.~ feature request
- [x] #4849 - Improper selection after paste, when allowInsertRow is disabled.
- [x] #4837 - [0.34.5+] updateSettings in afterSelectionEnd breaks copyPaste
- [x] #4790 - bug with pasting double quotation marks to cell
- [x] #4725 - Paste loses empty cells
- [x] #4717 - Table data copied from IE doesn't get pasted properly on chrome/firefox
- [x] #4456 - Pasting copied column, more spare rows added and first copied cell appears before additional spare rows
- [x] #4308 - Copy-paste from excel moves text to multiple cells
- [x] #4003 - Consecutive double quotes are not pasted correctly
- ~[ ] #888 - pasting from clipboard - error in afterChange hook~ `populateFromArray` needs refactoring

`* I would like to try to find a workaround for IE to make it possible.`

**Comment by wojciechczerniak** [comment]
Done!
