### ISSUE TITLE
ColumnSorting plugin review

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#4966]
### Description
An Epic issue to push our ColumnSorting plugin forward.

#### Stage 1
Fix few bugs:
- [ ] ~~Column sorting should not highlight the entire column #2151~~
- [x] Update `sortIndicator` after moving column #3900
- [x] Minimum column header width should allow space for `sortIndicator` #2533 
- [ ] Right mouse button (with ContextMenu enabled or not) should not trigger sort #4676
- [x] Sorting won’t work if column header contains HTML tag #4899 
- [x] `sortIndicator` needs a nice icon and maybe it should be aligned to the right
#### Stage 2 
- [ ] Add support for ColumnMeta #4902

```
getColumnMeta(column: number | string): ColumnSettings;
setColumnMeta(column: number | string, key: string, value: any): void;
setColumnMetaObject(column: number | string, meta: object): void;
```

Then:
- [x] Hide `sortIndicator` when `columnSorting` is disabled #3582
- [x] Make sure `disablePlugin()` method will clean up everything
- [x] Transfer sortFunction and sortIndicator into column properties #3313
- [x] With #3313 ready: Add ability to make some (but not all) columns sortable

#### Stage 3
New functionality: Add support for sorting by multiple columns #4590

- [x] Add tests first, define input and output scenarios
- [x] Implement <kbd>shift</kbd> + LMB click to sort by additional columns
- [x] Clicking on column that already is sorted should change the columns order in sort
- [x] Clicking on the same columns over and over again should allow to switch between all three states (ascending, descending, disable) we already support
- [x] Extend documentation for ColumnSorting plugin with example for multiple column sorting

#### Stage 4
- [ ] Documentation for ColumnSorting plugin says to check wiki but no such page exist
- [ ] Documentation for ColumnSorting plugin does not mention that you can click third time to disable sorting

**Comment by wojciechczerniak** [comment]
Most of the tasks for this stage are done. State 3 is described in #5442
