### ISSUE TITLE
Refactor Typescript definition files

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#5094]
### Description
Creating custom typed plugin is harder then it should. We also have few issues with wrappers and Handsontable PRO typing. This is in line with our plans to refactor package build system and will help with loading types.

- [ ] Internal types should be more exposed for plugin authors 
- [ ] Handsontable types should be extendable, presumably by using namespaces
- [ ] Each plugin should have their own type definition (or be a plugin written in TS)

Other:
- [x] `updateSettings` second argument should be optional (done in #5767)

### Connected Typescript issues we can address btw

- [ ] #5280 
- [x] #5428 
- [x] #5416 (PR #5425)
- [x] #5052 (PR ~#5721~ merged into #5767)
- [x] #5599 (PR ~#5719~ merged into #5767)
- [x] #5004 (PR #5767)
- [x] #5225  (PR #5767)
- [x] #5721 (PR #5767)
- [x] #5719 (PR #5767)
- [x] #5736 (PR #5767)
- [x] #5091 (PR #5767)
- [x] #5046 (PR #5767)
- [x] #5736 (PR #5767)
- [x] #4605
- [x] #4453 (PR #4519) 
- [x] #4455 (PR #4519) 
- [x] #5209 
- [x] #5211 
- [x] #5262

**Comment by wojciechczerniak** [comment]
Most of the work in this Epic is done. We will create new one when we will need further refactorings.
