### ISSUE TITLE
Improve the way we build Handsontable CE/PRO

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#5095]
### Description
We're looking for a better build and package management. With those changes we want to further modularize Handsontable and make another step toward smaller files and multiple NPM modules. By moving away from full builds we can better support wrappers and allow everyone to optimize size of their dependency on Handsontable.

### Stage 1
- [x] Build and publish Handsontable CE and PRO from monorepo (lerna.js?)
- [ ] Handsontable PRO should be an extension over Handsontable CE 
  - [ ] Cleanup wrappers to publish single package for both CE and Pro
- [x] Run tests for CE and Pro modules simultaneously 
- [ ] It should be possible to easily publish plugins as modules
  - [ ] Each plugin has it's own `d.ts` file so we can bundle them for `dist`
  - [ ] [Plugins should register under Handsontable namespace](https://github.com/webpack/webpack/tree/master/examples/multi-part-library) i.e. Handsontable.plugins.copyPaste
  - [ ] Deprecate `hot-builder`. Custom build should be as easy as `import` of required modules
- [ ] Update installation documentation with new instructions
- [ ] Update all examples or ~provide handsontable-pro.full.js for backward compatibility~
  - [ ] `handsontable-pro.js` is an extension to `handsontable.js` and we should use it like this so our users copy good patterns
- [x] Inconsistent in exporting Handsontable #4605 (although I think we should remove `browser` field from package.json)

### Stage 2
- [ ] We have few problems with polyfills
  - [x] Handsontable causing a parameter mismatch error with String.startsWith() #4599
  - [x] Overwriting global Promise.prototype #5398
  - [x] Handsontable writes named properties that overlap with Array.prototype methods #4217
  - [ ] We should create `handsontable-polyfill.js` or `handsontable-ie.js` as an optional file
- [ ] Move jQuery wrapper out of the main repo #5096
  - [ ] Add the documentation how to use Handsontable with jQuery

### Stage 3
- [ ] Add support for SCSS so we can slowly start to rewrite modules and use variables
- [ ] Add support for Typescript so we can rewrite modules one by one

### Possible solutions
- Lerna.js + Yarn Workspaces
- 🤔

**Comment by wojciechczerniak** [comment]
We're tracking this externally. This issue is no longer updated or relevant.
