### ISSUE TITLE
Global index mapper

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#5112]
### Description
We have problems with getting proper indexes translations sometimes. It's related to the current index mapping system basing on `modifyRow` / `unmodifyRow` and `modifyCol` / `unmodifyCol` hooks (it depends on the particular order of execution, which is described [here](https://github.com/handsontable/handsontable/issues/3328#issuecomment-272813589)).

**Connections between plugins (changing the sequence of rows).**

| 1st (left) -> 2nd (right) action | trimRows                                       | columnSorting               | manualRowMove
| -------------------------------- |:--------------------------------------:|:---------------------------:|:---------------------------------------:|
| trimRows                              | -                                                     | ✓¹                                   |  ✓²                                                   |
| columnSorting                      | ✓³                                                  | -                                      | [✘](http://jsfiddle.net/8o4qkaLo)⁴    | 
| manualRowMove                 | [✘](https://jsfiddle.net/2fvc15gu)⁵ | ✓⁶                                   | -                                                       |

1. Inside `columnSorting` plugin variable `blockPluginTranslation` is checked inside `onModifyRow` listener to always get data not already modified by the plugin translation (however it gets data modified by other plugins when calling `getDataAtCell` function).
2. To be described...
3. Inside `columnSorting` plugin the last set sorting is performed again inside `afterTrimRow` listener (called after trim row action).
4. No communication, problem when moving row from the sorted table.
5. No communication, problem when trimming after move row action.
6. Hook `modifyRow` is handled by `columnSorting` at first, so there is no communication. However, the problem doesn't occur. For `columnSorting` plugin previous sequence of indexes isn't needed. It just needs the proper relation between the index and the data. Then it introduces a completely new order of rows.

We should get proper indexes from the one place. Actions like `loadData`, `addRow` and `removeRow` could be handled by global index mapper (like shown on the below table), not like now (by every plugin in their own way).

**Suitable sequence of indexes after actions.**

|             | trimRows       | columnSorting               | manualRowMove
| ----------- |:--------------:|:---------------------------:|:-------------:|
| `loadData`  | reset          | reset                       | reset         |
| `addRow`    | remain         | remain (+ indicator change) | remain        |
| `removeRow` | remain         | remain (+ indicator change) | remain        |

### Task to be done: 

- [ ] Name of file and names inside `arrayMapper` should be changed.
- [ ] One common way of using "array mappers" inside plugins & cleanup of unnecessary functions (https://github.com/handsontable/handsontable/issues/5014, https://github.com/handsontable/handsontable/issues/5068, https://github.com/handsontable/handsontable/issues/5152).
- [ ] One common, refactored class from which will be created local index mappers (https://github.com/handsontable/handsontable/issues/5065).
- [ ] Global mapper which will handle mentioned above actions & new ones like `map`, `filter` & all needed removals from plugins.
- [ ] Removing indicator from `columnSorgin` plugin after `addRow` and `removeRow` actions.
- [ ] The `manualColumnFreeze` plugin separation from `manualColumnMove` (https://github.com/handsontable/handsontable/issues/4553).

### Related issue(s):

- https://github.com/handsontable/handsontable/issues/4567

**Comment by AMBudnik** [comment]
`inform` [`Mike`](https://forum.handsontable.com/t/gh-5112-column-freeze-sorting/3236) `after adding the mapper.`

**Comment by allanbowe** [comment]
Is there any update on this issue?  We need it for a customer feature (freeze column in combination with column sort)

**Comment by pnowak** [comment]
Hi @allanbowe 

We've just released 8.0.0-beta2 that fixes a lot of issues.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.

**Comment by allanbowe** [comment]
Thanks for the fast reply.  Is there any advice on how we can implement this, given we are using the `@handsontable/angular` wrapper?

**Comment by pnowak** [comment]
Unfortunately, we have to update all of our wrappers to support Handsontable 8.0.0 version. 

Here is an issue on Angular wrapper  - https://github.com/handsontable/angular-handsontable/issues/197
You should follow the mentioned issue.

**Comment by AMBudnik** [comment]
I believe that we can close this topic. Good job @wszymanski 🎖️
