### ISSUE TITLE
Refactor ES5 to ES6 code

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#5403]
### Description
Looks like some files are still in ES5. Quick refactor to ES6 will help us a lot.

- [ ] Editors:
  - [x] [BaseEditor](https://github.com/handsontable/handsontable/blob/master/src/editors/_baseEditor.js) PR: ~#5447~ ➡️ #5628
  - [x] [AutocompleteEditor](https://github.com/handsontable/handsontable/blob/master/src/editors/autocompleteEditor.js) PR: ~#5448~ ➡️ #5650
  - [x] [HandsontableEditor](https://github.com/handsontable/handsontable/blob/master/src/editors/handsontableEditor.js) PR: ~#5452~ ➡️ #5653
  - [x] [SelectEditor](https://github.com/handsontable/handsontable/blob/master/src/editors/selectEditor.js) PR: ~#5451~  ➡️ #5618
  - [x] [TextEditor](https://github.com/handsontable/handsontable/blob/master/src/editors/textEditor.js) PR: ~#5450~ ➡️ #5646
  - [ ] Update docs for custom editor https://handsontable.com/docs/6.2.0/tutorial-cell-editor.html (should solve https://github.com/handsontable/angular-handsontable/issues/127) Related docs issue: https://github.com/handsontable/docs/issues/21
- [x] Walkontable
  - [x] [Event](https://github.com/handsontable/handsontable/blob/master/src/3rdparty/walkontable/src/event.js) PR: #5655
- [x] [EditorManager](https://github.com/handsontable/handsontable/blob/master/src/editorManager.js) PR: #5683
- [x] [MultiMap](https://github.com/handsontable/handsontable/blob/master/src/multiMap.js) PR: #5660
- [x] [TableView](https://github.com/handsontable/handsontable/blob/master/src/tableView.js) PR: #5690
- [~DefaultSettings~](https://github.com/handsontable/handsontable/blob/master/src/defaultSettings.js)
- [x] [DataMap](https://github.com/handsontable/handsontable/blob/master/src/dataMap.js) PR: #5699 
- [~Core~](https://github.com/handsontable/handsontable/blob/master/src/core.js)

### Your environment
* Handsontable version: 5.0.2
* Browser Name and version: all
* Operating System: all

**Comment by aaronbeall** [comment]
I can help with this, would you accept PRs?

**Comment by aaronbeall** [comment]
Cool. Looking through a few of the file it looks like there's some ES6 there already, like `let`, `const`, and arrow functions. Is the main goal to convert constructors and prototype members to use `class` syntax?

**Comment by wojciechczerniak** [comment]
We did some work recently with `let` and `const` to fix ESLint warnings. You're right, that's the main goal. And to use native `class extends` instead `extend()` method (but we should keep it for backward compatibility if possible). If you have any other ideas let us know.

**Comment by aaronbeall** [comment]
@wojciechczerniak Are you using `static` or class property initializers?

**Comment by wojciechczerniak** [comment]
Sorry about the late answer. I've handed over the issue to the developers. They will explain everything during code review for PRs you've already started. BTW Great work, thanks!

**Comment by wojciechczerniak** [comment]
Released. Documentation for custom editor is tracked here https://github.com/handsontable/docs/issues/21
