### ISSUE TITLE
Refactored columnSorting plugin - stage 3

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#5442]
Some changes which would make the plugin more comprehensive:

- [ ] Sort should be passive, the `ObserveChanges` plugin should be removed, the `PersistantState` plugin should work properly when moved column by the `manualRowMove` plugin (it should reset sort state) #5649.
- [x] `TypeScript` definition file for plugin should be more strict, some tests should be added (#5445).
- [ ] The size of headers should be counted properly & feature should look properly on the [handsontable.com website](https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers&multi-column-sorting) - maybe scroll here is redundant (#5443)
- [ ] We should rethink what effect should be presented after removal of a column, which is sorted.
- [x] The bug related to the `blockPluginTranslation` variable inside the plugin should be fixed (#5446).
- [x] We should rethink whether sorting column by right mouse click should be possible (#5382, #4676).
- [ ] ~~We may register sorting functions to follow the `Open–closed principle`.~~
- [x] We should refactor the `MultiColumnSorting` plugin. It shouldn't duplicate the code (https://github.com/handsontable/handsontable-pro/issues/148).
- [ ] ~~We may refactor code to be more functional, i.e like in the [thenBy](https://github.com/Teun/thenBy.js) library.~~
- [ ] Sort function for booleans (#4683, https://github.com/handsontable/support/issues/15, #4047).

**Comment by aaronbeall** [comment]
Would also be great if it worked nicely with `NestedRows` plugin. :)

**Comment by AMBudnik** [comment]
After a short discussion with @wszymanski we decided that as most of the tasks were done in the past and the last task (https://github.com/handsontable/handsontable/issues/4047) is already developed and will be released in the new version we can close this epic and stick to 

* #5649
* #5443

as separate tasks to be completed.
