### ISSUE TITLE
Add parse-table to Handsontable.helpers

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#5684]
### Description
We need to make `parse-table` available externally as one of `Handsontable.helpers`.

Add support for:
- [x] Parse `THEAD` to Handsontable `settings.colHeaders` and back to `THEAD`
- [x] Parse `TR > TH` to Handsontable `settings.rowHeaders` and back to `TR > TH`
- [x] Import / Export merged cells
- [x] Fixed rows top/bottom
- [x] Nested headers
- [x]  #5826: Add carriage copy function
- [x]  #5622: Copy-paste to excel break text to multiple rows
- [x]  #5647: Carriage return inserted inside string when pasting from Excel, but not from text
- [x]  #5925: Parse `mso-ignore:colspan` (check rowspan)
- [x]  #5940: [6.1.0+] We can't paste merged data from Excel
- [x]  #5970: Paste multiline cells from googlesheet lost CRLF 

API:
- [x] `Handsontable.fromHTML()`
- [x] `Handsontable.fromString()`
- [x] `hot.toHTML()`;
- [x] `hot.toString()`;
