### ISSUE TITLE
New architecture for record translator

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#5751]
Edited by: @wojciechczerniak 

### Context
WIP

### Breaking changes
- `modifyRow`, `modifyCol`, `unmodifyRow` and `unmodifyCol` will be removed
- `manualColumnFreeze` will no longer enable `manualColumnMove` plugin and will work a liitle bit different.
- `collapsibleColumns` will no longer enable `hiddenColumns` plugins
- `nestedRows` will no longer enable `trimRows` plugin
- `filters` will no longer enable `trimRows` plugin
- `observeChanges` plugin won't be enabled by `columnSorting` and is from now deprecated
- `skipLengthCache` hook was removed
- Modifying data by reference and running `render()` does not work as it used to, because index mappers will not count this line. All operations must be done via Api methods `populateFromArray` (when cells are not readOnly - more details about [that](https://github.com/handsontable/docs/issues/74)) or `setDataAtCell`. 
- `minSpareRows` and `minRows` will ensure that number of visible rows is proper also when the `TrimRows` plugin is enabled.
- `toPhysicalRow` / `toPhysicalColumn` / `toVisualRow` / `toVisualColumn` functions won't return non-nullable index for unpresent element anymore. 
- Arguments of the `afterLoadData` has been changed.
- The `ManualColumnFreeze` plugin works in a different way.
- The `RecordTranslator` object and plugin's `t` property which referenced to it have been removed.
- Hooks after..., ie. `afterLoadData`, `afterFilter`, `afterUnmergeCells` are called just before a `render` call from now. 
- Modification of data stored in the table by reference won't be supported anymore.

For further explanations of changes please take a look at #5945. 

#### State 1
- [x] Create mappers collections where they can be registered
- [x] Register and modify mappers through reference
- [x] All mappers in collection should be updated on `remove`, `insert`, `loadData`, etc.
    - [x] Remove hooks from plugins
- [x] Stop using `modifyRow` and `modifyCol` hooks. Use `recordTranslator` instead.
    - [x] `undoRedo` plugin
    - [x] `dateValidator` validator
    - [x] `timeValidator` validator
- [x] Create `physicalCache` in IndexMapper class (for O(1) get operations)
- [x] Local Hook to rebuild Cache on changes

#### Stage 2

- [x] Fix all tests (in stage 1 they were ignored for fast prototyping)
- [x] Should work with `minRows`, `minCols`, `maxRows`, `maxCols` as before
- [x] Should work with `minSpareRows`, `minSpareCols` as before
- [x] Remove old RecordTranslator
- [x] Plugins should no longer use other plugins
    - [x] ManualColumnFreeze should no longer use ManualColumnMove
    - [x] NestedRows should no longer use TrimRows
    - [x] Filters should no longer use TrimRows
- [x] Rewrite all plugins index mapper mixins to register (and use) new IndexMapper
    - [x] TrimRows
    - [x] #5649 ColumnSorting and MultiColumnSorting
        - [x] Remove ObserveChanges dependancy
    - [x] #5152 ManualColumnMove
    - [x] #5068 ManualRowMove
    - [x] BindRowsWithHeaders (rewrite strategies as IndexMappers)
    - [x] Remove old IndexMapper mixin
- [ ] Rewrite plugins with arrays to use IndexMappers
    - [x] Formulas (nothing to do)
    - [x] Gantt Chart (nothing to do)
    - [x] ColumnSummary (nothing to do)
    - [ ] #6178 HiddenColumns
    - [ ] #6177 HiddenRows
    - [x] #6164 ManualRowResize
    - [x] #6163 ManualColumnResize 
    - [ ] #6170 AutoRowSize
    - [x] #6169 AutoColumnSize
- [x] Plugins should unregister their index mappers on destroy
- [x] Undo Redo support
- [x] Persistent State support
    - [x] Move ColumnSorting column meta manager to new indexMap
- [x] Batch operations to NOT rebuild Cache on every change

#### Stage 3a
- [ ] #6204 CollapsibleColumns should no longer use HiddenColumns plugin
- [ ] Cleanup and Code Review
  - [ ] Review all TODO and FIXME comments
  - [ ] Remove all magic strings, set them as `const`
- [ ] Write tests for all solved issues (related issues section bellow)
- [ ] Create documentation for IndexMappers
    - [ ] Update all references to old `modifyRow` pipeline
    - [ ] Update custom plugin tutorial with info how to use IndexMappers
    - [ ] Check if all breaking changes are reflected in the docs
- [ ] Deprecate `observeChanges` plugin in docs and in code (warning msg when enabled?)

#### Stage 3b (WIP by @budnix #6233)
- [ ] Refactor `cellMeta` and move it from `core.js` to data module
  - [ ] #5525, #5550, #6051 CRUD operations doesn't update `cellMeta`
  - [ ] #4902, #4901 Row / Column meta data based on indexMapper 
  - [ ] Cell meta has more dimensions than indexMapper, has to have own mechanism for that

### Releated issues
**Fixed:**

1.  - [x] #2685 `columnSorting` should work without `observeChanges`
2.  - [x] #3568 `manualMoveRow` don't work after `loadData`
3.  - [x] #3809 CRUD operations should work with `columnSorting` and `loadData`
4.  - [x] #3937 `Blank Rows in Middle of Grid [PRO]`
5.  - [x]  #3924 сolumnSummary does not work with columnSorting and context menu
6.  - [x] #4204 Using loadData on an object data doesn't work 
7.  - [x] #4121 `hiddenColumns` settings are reseted after `updateSettings`
8.  - [x] #4442 Filtering is using wrong indexes
9.  - [x] #4470 Wrong value after column move
10.  - [x] #4501 afterRowMove hook returns improper target parameter #4501 
11.  - [x] #4553 `manualColumnFreeze` should work without `manualColumnMove`
12.  - [x] #4567 `recordTranslator` shouldn't return `null` - need more test
13.  - [x] #4576 [0.27.0+] Data not render when use manualRowMove and minSpareRows 
14.  - [x] #4601 `manualColumnFreeze` should work with `columnSorting`
15.  - [x] #4666 Manual column width doesn't follow column if we insert / remove column 
16.  - [x] #4713 Row moving doesn't work with column sorting when PersistentState is enabled 
17.  - [x] #4926 `manualColumnMove` doesn't work when `data` object is empty
18.  - [x] #4999 `collapsibleColumns` doesn't work with `columnSorting`
19.  - [x] #5112 Global index mapper (EPIC, nothing to do here)
20.  - [x] #5065 Common rowsMapper for `columnSorting` `manualRowMove` and `trimRows` - nothing to test
21.  - [x] #5068 Refactor `manualRowMove` - nothing to test
22.  - [x] #5707 Filter causes Minsparerows to have problems 
23. - [x] #5173 problem with afterColumnMove
24.  - [x] #5178 `manualRowMove` should work with `filters`
25.  - [x] #5369 Handsontable colHeaders gets NaN on loadData 
26.  - [x] #5674 `htInvalid` should be updated on CRUD operations
27.  - [x] #5824 `skipColumnOnPaste` is broken with `columnSorting` enabled
28.  - [x] #5860 `trimRows` should work with `moveRow`
29.  - [x] #5862 `trimRows` does not work with `minSpareRows`
30.  - [x] #5889 `nestedRows` should work with `filters`
31.  - [x] #5890 `filters` should work with `columnSorting`
32.  - [x] #5915 `trimRows` should work with `filters`
33.  - [x] #5931 `manualColumnMove` doesn't work when `columns` count is different from array of objects properties count
34.  - [x] #5953 `trimRows` should work with `startRows`
35.  - [x] #5956 `columnSorting` is not working correctly with `loadData`
36.  - [x] #6005 afterColumnMove/beforeColumnMove doesn't tell you where the columns move to 
37.  - [x] #6278 Filters and `minSpareRows` problems at the same time - additional error fixed
38.  - [x] #6088 Duplicated rows while using `manualRowMove` with improper index
39.  - [x] #6310 Visual indexes are wrong when using trimRows and columnSorting 
40. - [x] #4480 `updateSettings` in `afterColumnMove` 
41. - [x] #5244  loadData() breaks column filters 
42. - [x] #5874 nestedRows does not allow to keep rowHeaders after collapsing 
43. - [x] #5900 Wrong position of buttons in nestedRows after use detach from parent
44. - [x]  #5794 ColumnSummary: Extra row + unchangeable values 
45. - [x] #6066  move multiple rows with `nestedRows` 
46. - [x] #6300 doesn't work with columnSummary when plugin tries to create a row  
47. - [x] #6339 Add `loadData` support for Nested Rows.
48. - [x] #3914 nested rows provokes error when removing and adding rows
49. - [x] #6086 Once we enable columnSorting we cannot run the merge() method 
50. - [x] #6412 After removing column rowHeaders stay improperly 

**Regression:**

None.

**Currently tested:**
- [ ] #6058 Performance and CPU wastage issue due to some handsontable properties. 

**Cell Meta**

Moved to #6274

**Not related to 5751**

1. ~#1501 Sorting passing logical index through afterChange event~
2. ~#3941 Auto column size plugin doesn't work properly after setting maxRows (by updateSettings)~
3. ~#4897 Wrong selection after inserting a row / column with `mergeCells` plugin enabled - `bug reproduced`~
4. ~#5100 Wrong 3rd parameter return for the beforeRemoveRow hook  - documentation changed~
5. ~#5270 Changing data while in edit results in edit to wrong data - **additional error**~
6. ~#5727 We shouldn't use interval to calculate cache length [there was a disscusion](https://github.com/handsontable/handsontable/issues/5727#issuecomment-532563665)~
7. ~#5208 Filtering results in blank rows - `hot.getPlugin("Filters").filter()` results~
8. ~#6004 ManualColumnMove dragging breaks after updateSettings()~
9. ~#3770 Rendering issue on column udpate~
10.  ~#5648 `filters` don't work with `copyPaste` when new row has to be created `bug reproduced`~
11. ~#5983 Sorting after filtering with minSpareRows set~
12. ~#6067 We cannot move nested row to become the last one in the table~
13. ~#4176 countSourceCols omits empty cells~
14. ~#5550 With enabled `formulas` the `sourceData` is not updated after remove column~
15. ~#4118 Issue with setDataAtRowProp() - bad column index translation~

**Found and repaired immediately**

1. - [x] #6292 [8.0.0-rc1] Visual width is improper after moving column 
2. - [x] #6320 [8.0.0-rc1] Newly inserted child row overwrites existing rows 
3. - [x] #6316 [8.0.0-rc1] Can't collapsed many parent of nestedRows.
4. - [x]  #6322 [8.0.0-rc1] Cells in Handsontable Editor no longer contain 'listbox' class.
5. - [x] #6410 [8.0.0-rc1] Column headers stay improperly after removing rows

 
**After HiddenColumns**

Moved to #6178

### Checklist
- [ ] Affected plugins:
  - [ ] `trimRows`
  - [ ] `nestedRows`
  - [ ] `manualColumnFreeze` / `manualRowFreeze`
  - [ ] `filters`
  - [ ] `manualRowMove` / `manualColumnMove`
  - [ ] `hiddenRows`  / `hiddenColumns`
  - [ ] `manualRowResize` / `manualColumnResize`
  - [ ] `autoRowResize` / `autoColumnResize`
  - [ ] `columnSorting` / `multipleColumnSorting`
  - [ ] `customBorders`
  - [ ] `collapsibleColumns`
  - [ ] `PersistantState`
  - [ ] `observeChanges` in wrappers

- [ ] Core functionalities:
  - [ ] `updateSettings`
    - [ ] What if I change `columns` property
    - [ ] What if `columns` is a function
    - [ ] Does it work with `minSpareRows` and `minSpareCols`
    - [ ] Does it work with `minRows`, `minCols`, `maxRows`, `maxCols`
  - [ ] `copy`, `cut` and `paste`
  - [ ] Cell validation
  - [ ] CRUD operations, `insertCol`, `removeCol`, `insertRow`, `removeRow`
     - [ ] Performance if we inser/remove 10 000 cols / rows vs Handsontable 7.1
     - [ ] Move rows between fixed top, fixed bottom and main overlays
     - [ ] Move columns between fixed left and main overlays

**Comment by aninde** [comment]
### Summary of testing related issues
### Releated issues
**Fixed:**

- [x] #2685 `columnSorting` should work without `observeChanges`
- [x] #3809 CRUD operations should work with `columnSorting` and `loadData`
- [x] #3937 `Blank Rows in Middle of Grid [PRO]`
- [x] #4121 `hiddenColumns` settings are reseted after `updateSettings`
- [x] #4442 Filtering is using wrong indexes
- [x] #4470 Wrong value after column move
- [x] #4501 afterRowMove hook returns improper target parameter #4501 
- [x] #4553 `manualColumnFreeze` should work without `manualColumnMove`
- [x] #4601 `manualColumnFreeze` should work with `columnSorting`
- [x] #4926 `manualColumnMove` doesn't work when `data` object is empty
- [x] #4999 `collapsibleColumns` doesn't work with `columnSorting`
- [ ] #5112 Global index mapper (EPIC, nothing to do here)
- [x] #5178 `manualRowMove` should work with `filters`
- [x] #5674 `htInvalid` should be updated on CRUD operations
- [x] #5824 `skipColumnOnPaste` is broken with `columnSorting` enabled
- [x] #5860 `trimRows` should work with `moveRow`
- [x] #5862 `trimRows` does not work with `minSpareRows`
- [x] #5889 `nestedRows` should work with `filters`
- [x] #5890 `filters` should work with `columnSorting`
- [ ] #5909 `hiddenColumns` stores visual indexes, should use physical
- [x] #5915 `trimRows` should work with `filters`
- [x] #5931 `manualColumnMove` doesn't work when `columns` count is different from array of objects properties count
- [x] #5953 `trimRows` should work with `startRows`
- [x] #5956 `columnSorting` is not working correctly with `loadData`

**Not fixed:**
- [ ] #6051 `cellMeta` should be updated with CRUD operations - need more test (will be tested today)
- [ ] #6063 `customBorders` should be updated with CRUD operations `bug reproduced`
- [ ] #6066 [8.0.0-rc1]  `columnSorting` does not work with `nestedRows` - `additional error`
- [ ] #6278 Filters and `minSpareRows` problems at the same time - `additional error`
- [ ] #3568 `loadData` should reset `manualRowMove` actions **changed to** `[8.0.0.-rc1] manualMoveRow don't work after loadData`
- [ ] #4381 `updateSettings` performance is very low because of `hiddenColumns` - `bug reproduced`
- [ ] #4567 `recordTranslator` shouldn't return `null` - need more test (will be tested today)
- [ ] #4666 Manual column width doesn't follow column if we insert / remove column  **partially fixed** read detail in [comment](https://github.com/handsontable/handsontable/issues/4666#issuecomment-532726444)
- [ ] #4897 Wrong selection after inserting a row / column with `mergeCells` plugin enabled - `bug reproduced`
- [ ] #5065 Common rowsMapper for `columnSorting` `manualRowMove` and `trimRows` - **nothing to test**
- [ ] #5068 Refactor `manualRowMove` - **nothing to test**
- [ ] #5208[8.0.0.-rc1] Filtering results in blank rows - `hot.getPlugin("Filters").filter()` results
- [ ] #5270 [8.0.0.-rc1] Changing data while in edit results in edit to wrong data - `additional error`
- [ ] #5525 [8.0.0.-rc1] CRUD operations doesn't update `cellMeta`
- [ ] #5550 With enabled `formulas` the `sourceData` is not updated after remove column
- [ ] #5571 `hiddenColumns` doesn't work with `columnSorting`
- [ ] #5598 [8.0.0.-rc1] `manualColumnMove` should work with `hiddenColumns`
- [ ] #5648 `filters` don't work with `copyPaste` when new row has to be created `Issue reproduced`
- [ ] #5727 We shouldn't use interval to calculate cache length
- [ ] #5875 `collapsibleColumns` should work without `hiddenColumns` `bug reproduced`

**Comment by wojciechczerniak** [comment]
Few more issues to check:

- [ ] #4713 Row moving doesn't work with column sorting when PersistentState is enabled 
- [ ] #5961 Row added during copy/paste operations and with hidden rows/columns enabled 
- [ ] #6067 We cannot move any element to become the last one in the table 
- [ ] #5983 Sorting after filtering with minSpareRows set 
- [ ] #6005 afterColumnMove/beforeColumnMove doesn't tell you where the columns move to 
- [ ] #5707 Filter causes Minsparerows to have problems 

After we finish `hiddenColumns`
- [ ] #4370 If the last column is a hidden column and stretchH is enabled, last column is being displayed 
- [ ] #5883 `hiddenColumns` plugin unsets cell's `renderer`
- [ ] #5847 [1.14.0+] Missing border left/top when use hiddenColumns/hiddenRows. 
- [ ] #5771  getSourceData functions return wrong data for nested rows

**Comment by wszymanski** [comment]
The `PersistantState` plugin hasn't been yet refactored. At now, it works just for 5 plugins such as: `ColumnSorting`, `MultiColumnSorting`, `ManualRowMove`, `ManualColumnMove`, `ManualRowResize` and `ManualColumnResize`. It may be handled by index mapper.

**Comment by AMBudnik** [comment]
Also fixed 
- [x] #6088 Duplicated rows while using manualRowMove with improper index

**Comment by wojciechczerniak** [comment]
Few more:
- [ ] #3770 Rendering issue on column udpate 
- [x] #4204 Using loadData on an object data doesn't work 
- [ ]  #3924 сolumnSummary does not work with columnSorting and context menu
- [ ] #4176 countSourceCols omits empty cells 
- [ ] #5369 Handsontable colHeaders gets NaN on loadData 
- [ ] #5244  loadData() breaks column filters 
- [ ] #3941 Auto column size plugin doesn't work properly after setting maxRows (by updateSettings) 
- [ ] #5100 Wrong 3rd parameter return for the beforeRemoveRow hook 
- [ ] #4118 Issue with setDataAtRowProp() - bad column index translation 

After hiddenColumns:
- [ ] #4716 Collapse not working correctly when using custom cell rendrers 
- [ ] #5704 hiddenColumns option interferes with keyboard movement. 
- [ ] #5588 autoRowSize renders wrong height after hiding column 
- [ ] #5877 hiddenRows/hiddenColumns doesn't work properly with autoWrapRow/autoWrapCol 
- [ ] #5817 Hiding first rows bug 
- [ ] #5847 Missing border left/top when use hiddenColumns/hiddenRows.

**Comment by aninde** [comment]
### Summary of testing related issues
**Fixed:**

1. - [x] #2685 `columnSorting` should work without `observeChanges`
2. - [x] #3568 `loadData` should reset `manualRowMove` actions **changed to** `[8.0.0.-rc1] manualMoveRow don't work after loadData`
3. - [x] #3809 CRUD operations should work with `columnSorting` and `loadData`
4. - [x] #3937 `Blank Rows in Middle of Grid [PRO]`
5. - [x]  #3924 сolumnSummary does not work with columnSorting and context menu
6. - [x] #4204 Using loadData on an object data doesn't work 
7. - [x] #4121 `hiddenColumns` settings are reseted after `updateSettings`
8. - [x] #4442 Filtering is using wrong indexes
9. - [x] #4470 Wrong value after column move
10. - [x] #4501 afterRowMove hook returns improper target parameter #4501 
11. - [x] #4553 `manualColumnFreeze` should work without `manualColumnMove`
12. - [x] #4567 `recordTranslator` shouldn't return `null` - need more test
13. - [x] #4576 [0.27.0+] Data not render when use manualRowMove and minSpareRows 
14. - [x] #4601 `manualColumnFreeze` should work with `columnSorting`
15. - [x] #4666 Manual column width doesn't follow column if we insert / remove column 
16. - [x] #4713 Row moving doesn't work with column sorting when PersistentState is enabled 
17. - [x] #4926 `manualColumnMove` doesn't work when `data` object is empty
18. - [x] #4999 `collapsibleColumns` doesn't work with `columnSorting`
19. - [x] #5112 Global index mapper (EPIC, nothing to do here)
20. - [x] #5065 Common rowsMapper for `columnSorting` `manualRowMove` and `trimRows` - nothing to test
21. - [x] #5068 Refactor `manualRowMove` - nothing to test
22. - [x] #5707 Filter causes Minsparerows to have problems 
23. - [x] #5178 `manualRowMove` should work with `filters`
24. - [x] #5369 Handsontable colHeaders gets NaN on loadData 
25. - [x] #5674 `htInvalid` should be updated on CRUD operations
26. - [x] #5824 `skipColumnOnPaste` is broken with `columnSorting` enabled
27. - [x] #5860 `trimRows` should work with `moveRow`
28. - [x] #5862 `trimRows` does not work with `minSpareRows`
29. - [x] #5889 `nestedRows` should work with `filters`
30. - [x] #5890 `filters` should work with `columnSorting`
31. - [x] #5915 `trimRows` should work with `filters`
32. - [x] #5931 `manualColumnMove` doesn't work when `columns` count is different from array of objects properties count
33. - [x] #5953 `trimRows` should work with `startRows`
34. - [x] #5956 `columnSorting` is not working correctly with `loadData`
35. - [x] #6005 afterColumnMove/beforeColumnMove doesn't tell you where the columns move to 
36. - [x] #6278 Filters and `minSpareRows` problems at the same time - additional error fixed
37. - [x] #6088 Duplicated rows while using `manualRowMove` with improper index


**Not fixed:**

1. - [ ] #1501 Sorting passing logical index through afterChange event 
2. - [ ] #3770 Rendering issue on column udpate 
3. - [ ] #3941 Auto column size plugin doesn't work properly after setting maxRows (by updateSettings) 
4. - [ ] #4118 Issue with setDataAtRowProp() - bad column index translation 
5. - [ ] #4176 countSourceCols omits empty cells 
6. - [ ] #4480 `updateSettings` in `afterColumnMove` error (**partially**)
7. - [ ] #5244  loadData() breaks column filters - fixed only partially
8. - [ ] #5550 With enabled `formulas` the `sourceData` is not updated after remove column - `bug reproduced`
9. - [ ] #5648 `filters` don't work with `copyPaste` when new row has to be created `bug reproduced`
10. - [ ] #5983 Sorting after filtering with minSpareRows set
11. - [ ] #6004 ManualColumnMove dragging breaks after updateSettings() 
12. - [ ] #6067 We cannot move nested row to become the last one in the table 

**Regression:**

1. - [ ] #5598 [8.0.0.-rc1] The column's data is being erased when we move column after a hidden area of columns. 
2. - [ ] #5909 [8.0.0.-rc1] The HiddenColumns plugin inconsistently interprets column indices
3. - [ ] #6066 [8.0.0-rc1]  `columnSorting` does not work with `nestedRows` - **additional error**
4. - [ ] #6292 Visual width is improper after moving column - **Regression**
5. - [ ] #6300 [8.0.0-rc1] doesn't work with columnSummary when plugin tries to create a row 


**Currently tested:**
- [ ] #5173 problem with afterColumnMove
- [ ] #6058 Performance and CPU wastage issue due to some handsontable properties. 


**Cell Meta, won't fix (not with 5751)**
- [ ] ~#5525 [8.0.0.-rc1] CRUD operations doesn't update `cellMeta` - `bug reproduced`~
- [ ] ~#6051 `cellMeta` should be updated with CRUD operations - need more test (will be tested tomorow)~
- [ ] ~#6063 `customBorders` should be updated with CRUD operations `bug reproduced`~

**Not related to 5751**

- [ ] ~#4897 Wrong selection after inserting a row / column with `mergeCells` plugin enabled - `bug reproduced`~
- [x] #5100 Wrong 3rd parameter return for the beforeRemoveRow hook  - documentation changed
- [ ] ~#5270 Changing data while in edit results in edit to wrong data - **additional error**~
- [ ] ~#5727 We shouldn't use interval to calculate cache length [there was a disscusion](https://github.com/handsontable/handsontable/issues/5727#issuecomment-532563665)~
- [ ] ~#5208 Filtering results in blank rows - `hot.getPlugin("Filters").filter()` results~


**After HiddenColumns**

Moved to #6178

**Comment by wojciechczerniak** [comment]
Shortcut: https://github.com/handsontable/handsontable/issues/5751#issuecomment-537859540

**Comment by wszymanski** [comment]
Link to PR: https://github.com/handsontable/handsontable/pull/5945

**Comment by aninde** [comment]
Shortcut: https://github.com/handsontable/handsontable/issues/5751#issuecomment-537859540

**Comment by aaronbeall** [comment]
Just want to say: I've been watching progress on this issue and the work is really impressive. The number of fixed issues are astounding. It's rare (in my experience) to see such a foundational refactoring come out alive. :)

**Comment by wojciechczerniak** [comment]
Thanks @aaronbeall ! We took our experience with the product from recent years, feedback from you and other developers, and decided to put it into good use. More is coming after this refactor. We're not done yet 😄
