### ISSUE TITLE
Adjust HiddenRows to new IndexMapper architecture

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#6177]
### Description
#5751 introduces a new architecture for index translation. We have to adjust HiddenRows plugin to be compatible with IndexMappers.

Changes have to base on `feature/issue-5751` branch.

### Tasks

- [ ] `hiddenRows` plugin refactor to use IndexMapper
    - [ ]  Use `hiddenCollection` index mapper added for hidden columns
    - [ ]  `skipRowOnPaste` should use `isHidden` from index mapper, not write this info each time to the cell meta (costly iteration over all cells and creating unnecessary lazy cell meta).
    - [ ]  `onAfterGetCellMeta` will not be needed? Sets CSS class and `skipRowOnPaste` for cells will be gone. But `afterHiddenRow` and `afterHiddenRow` might still be needed. Removing them mark as a breaking change.
    - [ ]  `resetCellMeta` will not be needed. Clears `skipRowOnPaste` in a loop over all cell meta, not the best for performance of `updateSettings`.
    - [ ]  `onAfterCreateRow` and `onAfterRemoveRow` will not be needed because keeping indexes in sync should be handled by the `indexMapper`
    - [ ]  `onModifyCopyableRange` should not be needed because `copyPaste` plugin should use the `indexMapper` to get the info about hidden rows
    - [ ]  We should remove `onBeforeSetRangeStartOnly` and `beforeSetRangeStart` and `beforeSetRangeEnd`. They are modifying selection, and we want selection to do its own translation if some indexes are hidden. Otherwise we would have to add those hook to each plugin that use `hiddenCollection` or implement it inside `indexMapper`. Same reasons as `hiddenColumn` and `hiddenRow` hooks. But we may keep those hooks.
    - [ ]  Remove `hiddenRow` hook. `fileExport` should ask `rowIndexMapper.isHidden()` method to get that info. Removing hook is a breaking change. * See breaking changes section.
    - [ ]  `onModifyRowHeight` should report `0.1` height for hidden rows. This should be last hook call in the pipeline, after `autoRowSize`, `manualRowSize`, settings rowHeights and the default 25px.
    - [ ]  In the method `isRowDataValid` move `this.hot.countRows()` out of the `every` loop. We can cache the value and do not recalculate count for each row.
    - [ ]  Remove `resetCellsMeta` call from `disablePlugin`
    - [ ]  We're adding `modifyCopyableRange` hook `onInit`. Is it registered again on each `settingsUpdate`? It's called on each `pluginUpdate`.
    - [ ]  Remove `afterRenderer` hook. We don't have to alter cells. They do not exist anymore.
    - [ ]  We should cache `this.hiddenRows` as `Set`. This will help to reduce number of `includes` loops, keeping distinct collection and limit `filter` calls over `hiddenRowsMap`. We can use local hook `change` to invalidate cache.

### Compatibility and tests

- How does it work when we move rows if some of them are hidden
- How does it work when we insert or remove new rows
- How does it work with copy & paste, and `skipHiddenRows` settings
- Does it `exportFile` correctly?
- Does `hiddenRows` work correctly with `trimRows`, `filters`, and `nestedRows`
- Are all `d.ts` definitions adjusted

### Related issues

- [x] #5588 autoRowSize renders wrong height after hiding column
- [ ] #5771 getSourceData functions return wrong data for nested rows
- [ ] #5817 Hiding first rows bug
- [ ] #5847 Missing border left/top when use hiddenRows.
- [ ] #5877 hiddenRows doesn't work properly with autoWrapRow/autoWrapCol
- [ ] #5961 Additional row added during copy/paste operations and with hidden rows/columns enabled
- [ ] #6113 We can show row when they're all hidden
- [ ] #6181 Row selection ignores columns that are hidden at the end
- [ ] #6224 Can't hide rows and merge cells at the same time
- [ ] #6376 Hiding rows while there is a merged area involved causes data shifting and unexpected merged area coordinates
- [ ] #6386 Wrong selection area after sorting with hidden rows
- [ ] #6905

**Comment by swistach** [comment]
It might be related: #5961

**Comment by AMBudnik** [comment]
`Self note: Update Zen 24070`

**Comment by aninde** [comment]
All related issues were tested with `v8.0.0`. The rest of the list was taken into account during the testing of version 8. 

Today I checked export again carefully with stable `v8.0.0` Closing as done.
