### ISSUE TITLE
Adjust HiddenColumns to new IndexMapper architecture

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#6178]
### Description
#5751 introduces a new architecture for index translation. We have to adjust HiddenColumns plugin to be compatible with IndexMappers.

Changes have to base on `feature/issue-5751` branch.

### Tasks

- [ ] Extend `indexMapper` with `hiddenCollection`
    - [x] Add hiddenCollection to indexMapper
    - [x] Rename indexMapper translator methods: `toPhysical` and `toVisual`. We have now more methods and combinations with `renderable` indexes included.
    - [x] Add translation between Selection and Highlight (Walkontable Selection) classes
    - [x] Add translation between Selection Event in Walkontable and Selection class in Handsontable
    - [x] Handsontable: Data should be available through `getData` and copyable
    - [x] Walkontable: Do not render hidden rows/columns and their TDs in DOM
    - [ ] Walkontable: Remove `.hide` CSS
    - [ ] Walkontable: Remove adding/removing `hide` class
    - [ ] Ghosttable: Should ignore hidden columns/rows in calculations (should it?)
    - [ ] Adjust `nestedHeaders` to `hiddenCollection`. Columns are now longer rendered, so `colspan` should be calculated without them.
    - [ ] Adjust `collapsibleColumns` plugin to `hiddenCollection`. When collapsing / expanding columns the `colspan` has to be calculated correctly. Even if there are hidden columns somewhere in between.
- [ ] `hiddenColumns` plugin refactor to use IndexMapper
    - [x] Use `hiddenCollection` to track hidden columns
    - [x] Remove `isPhysicalIndex` argument from `isHidden` method. Translate index manually where it was needed.
    - [x] `onAfterCreateCol` and `onAfterRemoveCol` are not needed anymore. IndexMapper will handle CRUD operations
    - [x] `onAfterGetCellMeta` will not be needed. We're not going to overwrite renderers with empty one anymore. Check if `afterHiddenColumn` and `firstVisibleColumn` CSS classes are needed. Removing them mark as a breaking change.
    - [ ] Move `skipColumnOnPaste` handling to copy & paste. Use `isHidden` from index mapper and do not use `hiddenColumns` plugin in any way.
    - [ ] `beforeStretchingColumnWidth` should not be called for hidden columns. We can remove handler for this hook. Should be mentioned as a breaking change together with not calling `getColHeader` hook as a consequence of not displaying TDs in DOM.
    - [x] Remove `hiddenColumn` hook. `fileExport` should ask `columnIndexMapper.isHidden()` method to get that info. Removing hook is a breaking change.  * See breaking changes section.
    - [x] Remove `afterRenderer` hook. Do we need to alter cells in any way?
    - [x] Remove unnecessary `this.hot.render()` on plugin disable
    - [ ] Remove `resetCellsMeta` on plugin disable
    - [x] In a method `isColumnDataValid` move `this.hot.countCols()` out of the loop. It's not necessary to recalculate columns count each time. Lets cache it.
    - [x] `onModifyColWidth` should return `0` height for hidden columns. This should be last hook call in the pipeline, after `autoColumnSize`, `manualColumnSize`, settings for columnWidths and the fault 50px.
    - [ ] We should cache `this.hidden`Columns as `Set`. This will help to reduce number of `includes` loops, keeping distinct collection and limit `filter` calls over `hiddenColumnsMap`. We can use local hook `change` to invalidate cache.

### Tests and compatibility

To avoid unnecessary rendering of hidden columns, we have to improve/add a few things:
- [x] `Core.getCell()` should return `null` for hidden columns between the first rendered column and the last rendered column,
- [x] `Core.getColHeader()` should support hidden columns,
- [x] `Core.getColWidth()` should return `0` for hidden columns,
- [x] `Core.getSelected*()` should return indexes of selected cell ranges, including hidden columns
- [x] Walkontable should base rendering only on visible columns (hidden elements shouldn't be present in DOM),
- [x] How does it work when we move columns if some of them are hidden
- [x] How does it work when we insert or remove new columns
- [x] How does it work with copy & paste, and `skipHiddenRows`, `skipHiddenColumns` settings
- [x] Does it `exportFile` correctly?
- [ ] Does `hiddenColumns` and `collapsibleColumns` work together correctly?
- [x] Are all `d.ts` definitions adjusted
- [x] `hiddenColumns` should work with `stretchH`
- [x] `hiddenColumns` should work with `manualColumnResize`

### Related issues

- [ ] #4121 Hidden columns become visible when we run updateSettings
- [ ] #4181 using 'hiddenColumns' and 'stretchH' shows a unnecessary horizontal scrollbar when there is enough space
- [ ] #4370 If the last column is a hidden column and stretchH is enabled, last column is being displayed
- [ ] #4381 `updateSettings` performance is very low because of `hiddenColumns`
- [ ] #4631 Broken height header when use column height and hidden column setting
- [ ] #4716 Collapse not working correctly when using custom cell rendrers
- [ ] #5015 [1.8.2+] Incorrect header name
- [ ] #5571 `hiddenColumns` doesn't work with `columnSorting`
- [ ] #5598 [8.0.0.-rc1] `manualColumnMove` should work with `hiddenColumns`
- [ ] #5704 hiddenColumns option interferes with keyboard movement.
- [ ] #5847 Missing border left/top when use hiddenColumns.
- [ ] #5871 Hiding columns affect selection of hidden columns
- [ ] #5875 `collapsibleColumns` should work without `hiddenColumns`
- [ ] #5877 hiddenColumns doesn't work properly with autoWrapRow/autoWrapCol
- [ ] #5881 When we hide first column on IE we get double border for top left corner
- [ ] #5882 Indexes of nestedHeaders are not recalculating after remove/add column
- [ ] #5883 `hiddenColumns` plugin unsets cell's `renderer`
- [ ] #5909 `hiddenColumns` stores visual indexes, should use physical
- [ ] #5961 Additional row added during copy/paste operations and with hidden columns enabled
- [ ] #6113 We can show columns when they're all hidden
- [ ] #6181 Row selection ignores columns that are hidden at the end
- [ ] #6426 When we define data with more data than used in `columns` we cannot `show column` once it's hidden
- [ ] #6376 Hiding rows while there is a merged area involved causes data shifting and unexpected merged area coordinates
- [ ] #6395 Some headers are gone if we hide and show them again
- [ ] #6463 [8.0.0-beta.1] colHeader is truncated after moving hiddenColumn
- [ ] #6557 Hidden (last) column is visible upon resizing Columns
- [ ] #6668 Column hiding issue after columns moved manually 
- [ ] #6742 Paste off-by-one after show/hide column 
- [ ] #6743 Too many values pasted when column is hidden

**Comment by wojciechczerniak** [comment]
### Related issues
- [ ] #4370 If the last column is a hidden column and stretchH is enabled, last column is being displayed 
- [ ] #4381 `updateSettings` performance is very low because of `hiddenColumns` - `bug reproduced`
- [ ] #4716 Collapse not working correctly when using custom cell rendrers 
- [ ] #5571 `hiddenColumns` doesn't work with `columnSorting`
- [ ] #5588 autoRowSize renders wrong height after hiding column 
- [ ] #5598 [8.0.0.-rc1] `manualColumnMove` should work with `hiddenColumns` 
- [ ] #5704 hiddenColumns option interferes with keyboard movement. 
- [ ] #5771  getSourceData functions return wrong data for nested rows 
- [ ] #5817 Hiding first rows bug 
- [ ] #5847 Missing border left/top when use hiddenColumns/hiddenRows. 
- [ ] #5875 `collapsibleColumns` should work without `hiddenColumns`
- [ ] #5877 hiddenRows/hiddenColumns doesn't work properly with autoWrapRow/autoWrapCol 
- [ ] #5883 `hiddenColumns` plugin unsets cell's `renderer`
- [ ] #5909 `hiddenColumns` stores visual indexes, should use physical 
- [ ] #5961 Additional row added during copy/paste operations and with hidden rows/columns enabled

**Comment by wszymanski** [comment]
I will commit changes rebased with develop, so some changes may be shown here once again.

**Comment by wszymanski** [comment]
Merged with the actual develop branch once again.

**Comment by wszymanski** [comment]
Rebased once again commits (fixed a problem within 1975b4f93dbfc12fddd07f965df07d9219b56d02 which didn't occur when @swistach committed).

**Comment by wszymanski** [comment]
There was removed `hiddenColumn` hook within commit: https://github.com/handsontable/handsontable/commit/a80e9712d6e182b0017264bbac0da47ec8ff1435. It is a breaking change.

Was:

`hot.hasHook('hiddenColumn') && this.hot.runHooks('hiddenColumn', column)`

Will be:

`hot.columnIndexMapper.isHidden(physicalColumnIndex)`

**Comment by wojciechczerniak** [comment]
@wszymanski @budnix commited deprecated/removed hooks API. This hook should be added to the list.

**Comment by wszymanski** [comment]
🔴 New breaking change: So far, up to Handsontable 8.0 the [listen](https://handsontable.com/docs/7.4.2/Core.html#listen) function has been handling extra parameter `modifyDocumentFocus`.

For tests, if focus and `CopyPaste` plugin works properly:

- when there are at least two instances of Handsontable
- an instance is wrapped by `iframe`
- when [outsideClickDeselects](https://handsontable.com/docs/7.4.2/Options.html#outsideClickDeselects) option is set
- when option [editor](https://handsontable.com/docs/7.4.2/Options.html#editor) is set fo `false`
- when option [uiContainer](https://handsontable.com/docs/7.4.2/CopyPaste.html#uiContainer) for the `CopyPaste` plugin was set (https://github.com/handsontable/handsontable/issues/5686)
- when the `Filters` plugin is enabled
- when `DropdownMenu` and `ContextMenu` plugins are enabled
- when [fragmentSelection](https://handsontable.com/docs/7.4.2/Options.html#fragmentSelection) option is set
- with IME (https://github.com/handsontable/handsontable/issues/4662, `Chinese Pinyin - Simplified`)
- when there is an external input element in DOM
- with [Filter as you type](https://handsontable.com/docs/7.4.2/demo-filtering.html#custom-implementations) demo
- copying data by system's menu bar and keyboard shortcuts (`cmd` + `c`, `cmd` + `v`, `cmd` + `x`)
- [different editors](https://handsontable.com/docs/7.4.2/Options.html#editor)
- there is no regression on the IE9+ (may be related to [this line](https://github.com/handsontable/handsontable/commit/7be883c433d708106d22a6a43dbf80f720316a18#diff-05667cff20bca6e939bc776de97d8b7bR172))

FYI: @aninde, I will help if something is unclear.

**Comment by wszymanski** [comment]
🔴 Breaking change:
- LMB click on the corner will select all cells.
- RMB click on the corner when there is no data will show all options disabled:
  - except `Insert column right` and `Insert row below` when a table has data type defined by `dataSchema` as `array`.
  - except `Insert row right` otherwise

I left old work of RMB click when [there are rows, but no columns](https://github.com/handsontable/handsontable/issues/6733). However, for me, it's a bug. Behavior, in this case, should be thought out.

**Comment by wszymanski** [comment]
🔴 Breaking change: Hidden indexes aren't rendered. As a consequence `modifyColWidth` will be executed just for some of the rows (just the rendered ones).

**Comment by wszymanski** [comment]
🔴 Breaking change: The `getColWidth` for hidden index will return `0` (it returned `0.1` so far).

**Comment by wszymanski** [comment]
🔴 Breaking change: The `getColWidth` for hidden index will return `0` (it returned `0.1` so far).

FYI: @scarletfog

**Comment by wojciechczerniak** [comment]
We no longer need this epic.
