### ISSUE TITLE
CollapsibleColumns should no longer use HiddenColumns plugin

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6204]
### Description
- [ ] We need `hiddenCollection` #6178
- [ ] Use `hiddenCollection` instead of `hiddenColumns` plugin
- [ ] Both plugins should use this `hiddenCollection` with their own `valueMap`
- [ ] Data Manager should have new method `getRenderableData(...)` for walkontable use
- [ ] Hidden columns / rows should not be renderer in the view
- [ ] But they should be copy-able 
- [ ] It should be possible to hide a column that is a part of collapsible section and when the section is expanded that column should remain hidden.

### Issues that may be fixed by this refactor

- [x] Expand collapsed column, is expanding also 'child' collapsed columns, except the first child #5792 
- [ ] collapseAll method for collapsibleColumns doesn't work with sorting enabled (observeChanges) #4999

**Comment by AMBudnik** [comment]
This issue is no longer accurate.
