### ISSUE TITLE
CellMeta Refactor

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6274]
### Description

We want to achieve here an event or hook that we can use later in Walkontable. Rendering engine needs to be notified of changes in meta data `className`, `style` and other that could affect renderer output. Small refactor might be necessary.

### Scope ?

Here are all ideas I have about cellMeta:

- [ ] Move `cellProperties` code from `core.js` to more appropriate place
- [ ] Move cellMeta, dataMap and recordTranslator under one directory, our future `DataManager`
- [ ] Observing CRUD operations: `createColumn`, `createRow`, `removeColumn`, `removeRow`, `moveColumn` and `moveRow` handsontable/dev-handsontable#130
- [ ] CRUD operations should work reliable, sometimes they are not updated correctly handsontable/handsontable#6051 handsontable/handsontable#6063
- [ ] A mechanism to observe changes inside single `cellMeta` object. `defineProperty` or `Proxy` object
- [ ] Events / hooks that will be triggered when change is observed 
- [ ] Performance improvement idea: `getCellMeta` can memoize results for `row`, `col` call and return same cell meta with `O(1)` complexity during rendering cycle. We need then to reset the memoized cache after end of each render cycle.
- [ ] Performance improvement idea: With `Proxy` object, we don't have to rewrite `col`, `row`, `visualRow`, `visualCol`, `instance` as object peach time we request / create cellMeta object. We can have a `get` handler that will handle those values for us.
- [ ] We will store cellMeta as an array of arrays like we do so currently. Unless we find a better idea?
- [ ] Add setCellMetaAtRow and setCellMetaAtCol handsontable/handsontable#5966 (and batch the loop) 
- [ ] add `setRowMeta`, `getRowMeta` methods handsontable/handsontable#4901 (we can use indexMapper to store them)
- [ ] add `setColumnMeta`, `getColumnMeta` methods handsontable/handsontable#4902 (we can use indexMapper to store them)
- [ ] alter('insert_col') and alter('insert_row') don't support null as an index handsontable/handsontable#4448

### Related issues

- [x] handsontable/handsontable#5550 after remove columns get wrong sourceData with formulas enabled 
- [x] handsontable/handsontable#5635 Formulas don't update after row is removed 
- [x] handsontable/handsontable#4654 After inserting a row, an auto-updated formula displays incorrect value 
- [ ] handsontable/handsontable#5525 [8.0.0.-rc1] CRUD operations doesn't update `cellMeta`
- [ ] handsontable/handsontable#6051 `cellMeta` should be updated with CRUD operations 
- [ ] handsontable/handsontable#6063 `customBorders` should be updated with CRUD operations
- [ ] handsontable/handsontable#5051 We're not able to change cell type on the fly 
- [ ] handsontable/handsontable#4793 Cell type cannot be changed via setCellMeta
- [ ] handsontable/handsontable#4360 When changing cell type, cell editor does not dynamically change 
- [ ] handsontable/handsontable#5543 Error after update settings rendering twice and picking wrong renderer functions  

### Other notes

Various ideas and notes.

#### Pseudo code
Might be helpful. **Not a final API**.

```typescript

class Core {
  alter(op, index) {
    switch op {
      case 'remove_col': return this.dataManager.removeColumn(index);
    }
  }
}

class DataManager {
  removeColumn(columnsToRemove: number | number[]): void {
    this.sourceData.removeColumn(columnsToRemove);
    this.metaData.removeColumn(columnsToRemove);
    this.recordTranslator.removeColumn(columnsToRemove);
  }
}

interface DataCRUD {
  createColumn: (index: number | number[]) => boolean;
  createRow: (index: number | number[]) => boolean;
  deleteColumn: (index: number | number[]) => boolean;
  deleteRow: (index: number | number[]) => boolean;
  moveColumn: (index: number | number[], destination: number) => boolean;
  moveRow: (index: number | number[], destination: number) => boolean;

  // if multiple data OPs are possible, we should batch them
  batch(callback: () => {}): void;

  constructor( ? ): DataCRUD;
  destroy(): void;
}

interface SourceData extends DataCRUD {
  getData: (row: number, col: number) => any;
  setData: (row: number, col: number, value: any) => boolean;
}

interface MetaData extends DataCRUD {
  getCellMeta: (index: number) => CellMeta;
  setCellMeta: (index: number, CellMeta) => boolean;
  getColumnMeta: (index: number) => ColumnMeta;
  setColumnMeta: (index: number, ColumnMeta) => boolean;
  getRowMeta: (index: number) => RowMeta;
  setRowMeta: (index: number, RowMeta) => boolean;
}

interface RecordTranslator extends DataCRUD {
  toVisualRow(row: number): number;
  toVisualColumn(column: number): number;
  toVisual(row: number, column: number): [number, number];
  toPhysicalRow(row: number): number;
  toPhysicalColumn(column: number): number;
  toPhysical(row: number, column: number): [number, number];
}
```

#### Solving callback order issue

```typescript
class DataManager {
  removeColumn(columnsToRemove: number | number[]): void {
    const result = this.instance.runHooks('beforeRemoveColumn', args);	

    if (result !== false) {
      this.sourceData.removeColumn(columnsToRemove);
      this.metaData.removeColumn(columnsToRemove);
      this.recordTranslator.removeColumn(columnsToRemove);
    }

    this.instance.runHooks('afterRemoveColumn', args);	
  }
}
```

Where currently hooks are called inside `dataMap.js` (sourceData) so this works like...
```typescript
class DataManager {
  removeColumn(columnsToRemove: number | number[]): void 
    this.instance.runHooks('beforeRemoveColumn', args);	
    
    this.sourceData.removeColumn(columnsToRemove);

    this.instance.runHooks('afterRemoveColumn', args);	

    this.metaData.removeColumn(columnsToRemove);
    this.recordTranslator.removeColumn(columnsToRemove);
		
  }
}
```
... and as a result if in the `afterRemoveColumn` hook we call `getCellMeta` we will get an array which is not yet updated. Issue handsontable/handsontable#5525

**Comment by aninde** [comment]
I tested with @AMBudnik [**Related issues**](https://github.com/handsontable/handsontable/issues/6274#issue-495617991). Unfortunately, despite many good changes and the fact that PR itself works well, it does not improve any of these reported bugs. Repairing these bugs did not belong to the scope of this pull request, so it does not affect its merge to develop.

**Comment by AMBudnik** [comment]
Mentioned issue #4654 is fixed in v9 (RN https://github.com/handsontable/handsontable/releases/tag/9.0.0). I've checked in on the list.

**Comment by sl01k** [comment]
Closing this epic. Many of the items listed here have been addressed over subsequent releases (e.g. formula-related CRUD issues fixed in v9, indexMapper improvements, etc.), and the remaining items are outdated and no longer align with the current architecture.

If any specific sub-issue is still relevant, it should be tracked in its own dedicated issue.
