### ISSUE TITLE
Configurable ContextMenu's container

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#6283]
### Description
Due to we still need to rethink how configurable container for editors should work, we decided to move part of #6202 scope about ContextMenu to the separated issue.

To-do list:
- [x] New option in the settings object - where the plugin should insert elements
- [x] If the container's not set we should have a default element (for backward compatibility)

Additionally we can fix:
- [x] #3446 - ContextMenu should not open another instance if a user clicked <kbd>RMB</kbd> on the command item
- [x] #5846 - native context menu should not call `mousemove`'s callback in the `dragToScroll` plugin
- [ ] ~#6218 - ContextMenu should not allow to open native context menu on itself~

**Comment by aninde** [comment]
Demo for testing https://jsfiddle.net/ka5ub68q/. Works as intended. `contextMenu` and `dropdown Menu` are visible and are not cropped by iframe, when they have  `uiContainer: document.getElementById('childlessParent')`.
