### ISSUE TITLE
8.0.0 release

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6465]
### Description

Various tasks that we want to address before releasing v8.0.0.

*   [x] #5751 indexMappers without hiddenIndexes
*   [x] #6178 Extend indexMapper with hiddenCollection
*   [x] #6178 hiddenColumns plugin refactor to use IndexMapper
*   [x] #6204 Remove the connection between collapsibleColumns and hiddenColumns plugins
*   [x] #6177 hiddenRows plugin refactor to use IndexMapper
*   [x] handsontable/techwrite#4 Update documentation and examples
*   [x] remove `beforeChangeResult` as a function check and warning (Handsontable v0.12 was a very long time ago)
    * [ ]  [#4-PR](https://github.com/handsontable/techwrite/pull/4) Prepare migration guide for breaking changes
    * [x]  [#6541-PR](https://github.com/handsontable/handsontable/pull/6541) Remove "experimental" tag from `ganttChart`, `formulas` and `nestedRows`
*   [x] Deprecate IE support. Remove IE from the documentation.
    * [x]   [#6541-PR](https://github.com/handsontable/handsontable/pull/6541) Deprecate `observeChanges` plugin. Add a console warning when the plugin is enabled.
    * [x] [#6541-PR](https://github.com/handsontable/handsontable/pull/6541) Deprecate `ganttChart` plugin. Add a console warning when the plugin is enabled.
*   [x] Remove `post-install` warning about v7.0.0 MIT license change. #6608
*   [x] Update README.md logo and screenshot for HiDPI screens (Retina) #6609
*   [x] Add a warning messege for removed hooks:  
    `Plugin hook "modifyRow" was removed in Handsontable 8.0.0. Please consult release notes <link> to learn about the migration path` #6613
*   [x] Update deps #5159, #6610
    *   `moment.js` to `2.24.0`5674
    *   `pikaday` to `1.18.0`
    *   `numbro` to `2.1.2` (check minified build #5790)
*   [x] #6525 Remove helpers that cover IE8 or not needed anymore

### After code freeze

*   [ ] Check performance and compare with 7.x.x branch

### Checklist

1. * [x] #2685 `columnSorting` should work without `observeChanges`
1. * [x] #3328  beforeColumnResize and beforeRowResize first argument is column width 
1. * [x] #3568 `manualMoveRow` don't work after `loadData`
1. * [x] #3726 Cannot Navigate Past Hidden Column Using Keyboard if hot.updateSettings is Called in AfterSelection
1. * [x] #3770 Rendering issue on column udpate with updateSettings
1. * [x] #3809 CRUD operations should work with `columnSorting` and `loadData`
1. * [x] #3914 & #5133`nestedRows` should work with `InsertRow`, `RemoveRow` operations, 
1. * [x] #3924 сolumnSummary does not work with columnSorting and context menu
1. * [x] #3937 `Blank Rows in Middle of Grid [PRO]`
1. * [x] #3958 DataSource.countColumns returns invalid number of columns for nested objects.
1. * [x] #3978 afterOnCellMouseDown returns coords (0,0) after click on the topleft corner
1. * [x] #4121 `hiddenColumns` settings are reseted after `updateSettings`
1. * [x] #4154 formulas not init with nestedRows
1. * [x] #4176 Headers doesn’t export with exportToFile in the specific case 
1. * [x] #4181 using 'hiddenColumns' and 'stretchH' shows a unnecessary horizontal scrollbar when there is enough space
1. * [x] #4204 Using loadData on an object data doesn't work
1. * [x] #4233 Drag down: can't return back to the original cell
1. * [x] #4360 When changing cell type, cell editor does not dynamically change
1. * [x] #4370 If the last column is a hidden column and stretchH is enabled, last column is being displayed
1. * [x] #4381 `updateSettings` performance is very low because of `hiddenColumns`
1. * [x] #4441 Allow cancelling of autofill in the beforeAutofill hook
1. * [x] #4442 Filtering is using wrong indexes
1. * [x] #4470 Wrong value after column move
1. * [x] #4480 `updateSettings` in `afterColumnMove`
1. * [x] #4501 afterRowMove hook returns improper target parameter 
1. * [x] #4553 `manualColumnFreeze` should work without `manualColumnMove`
1. * [x] #4567 `recordTranslator` shouldn't return `null` - need more test
1. * [x] #4576 \[0.27.0+\] Data not render when use manualRowMove and minSpareRows
1. * [x] #4601 `manualColumnFreeze` should work with `columnSorting`
1. * [x] #4666 Manual column width doesn't follow column if we insert / remove column
1. * [x] #4713 Row moving doesn't work with column sorting when PersistentState is enabled
1. * [x] #4716 Collapse not working correctly when using custom cell rendrers
1. * [x] #4793 Cell type cannot be changed via setCellMeta
1. * [x] #4897 Improper selection after insert column/row when mergeCells is enabled.
1. * [x] #4926 `manualColumnMove` doesn't work when `data` object is empty
1. * [x] #4999 `collapsibleColumns` doesn't work with `columnSorting`
1. * [x] #5000 Incorrect data is returned after undoing the remove column option
1. * [x] #5065 Common rowsMapper for `columnSorting` `manualRowMove` and `trimRows` - nothing to test
1. * [x] #5068 Refactor `manualRowMove` - nothing to test
1. * [x] #5112 Global index mapper (EPIC, nothing to do here)
1. * [x] #5159 Update deps
1. * [x] #5173 problem with afterColumnMove
1. * [x] #5178 `manualRowMove` should work with `filters`
1. * [x] #5200 `manualColumnMove` doesn't modify the `columns` in `updateSettings`
1. * [x] #5207 Persisted manualColumnMove not restored when using loadData()
1. * [x] #5208 Filtering results in blank rows 
1. * [x] #5244 loadData() breaks column filters
1. * [x] #5328 Update data doesn't work with collapsed/trimmed rows? 
1. * [x] #5369 Handsontable colHeaders gets NaN on loadData
1. * [x] #5388 Add `beforeSetCellMeta` hook with an ability to cancel the changes 
1. * [x] #5571 `hiddenColumns` doesn't work with `columnSorting`
1. * [x] #5591 The "manualColumnMove" operation affects the column order of data loaded by "loadData". 
1. * [x] #5598 \[8.0.0.-rc1\] `manualColumnMove` should work with `hiddenColumns`
1. * [x] #5704 hiddenColumns option interferes with keyboard movement.
1. * [x] #5707 Filter causes Minsparerows to have problems
1. * [x] #5753  Nested rows bad state after changing data 
1. * [x] #5771 getSourceData functions return wrong data for nested rows
1. * [x] #5792 Expand collapsed column, is expanding also 'child' collapsed columns, except the first child 
1. * [x] #5794 ColumnSummary: Extra row + unchangeable values
1. * [x] #5817 Hiding first rows bug
1. * [x] #5824 `skipColumnOnPaste` is broken with `columnSorting` enabled
1. * [x] #5849 [2.0.0+] Scrolls to the end when columns are updated such that the selected column is removed 
1. * [x] #5860 `trimRows` should work with `moveRow`
1. * [x] #5861 currentColClassName doesn't work properly with nestedHeaders
1. * [x] #5862 `trimRows` does not work with `minSpareRows`
1. * [x] #5871 Hiding columns affect selection of hidden columns
1. * [x] #5874 nestedRows does not allow to keep rowHeaders after collapsing
1. * [x] #5875 `collapsibleColumns` should work without `hiddenColumns`
1. * [x] #5877 hiddenColumns doesn't work properly with autoWrapRow/autoWrapCol
1. * [x] #5881 When we hide first column on IE we get double border for top left corner
1. * [x] #5882 Indexes of `nestedHeaders` are not recalculating after remove/add column 
1. * [x] #5883 `hiddenColumns` plugin unsets cell's `renderer`
1. * [x] #5889 `nestedRows` should work with `filters`
1. * [x] #5890 `filters` should work with `columnSorting`
1. * [x] #5900 Wrong position of buttons in nestedRows after use detach from parent
1. * [x] #5906 Selection of a whole row does not happen consequently after selecting a row header.
1. * [x] #5909 `hiddenColumns` stores visual indexes, should use physical
1. * [x] #5915 `trimRows` should work with `filters`
1. * [x] #5931 `manualColumnMove` doesn't work when `columns` count is different from array of objects properties count
1. * [x] #5953 `trimRows` should work with `startRows`
1. * [x] #5956 `columnSorting` is not working correctly with `loadData`
1. * [x] #5999 handsontable 7.0.2 context menu issue with multiple selected rows in case of 1st column hidden 
1. * [x] #6005 afterColumnMove/beforeColumnMove doesn't tell you where the columns move to
1. * [x] #6035 The function loadManualRowHeights is return a array, but in the typescript .d.ts file it is defined as void
1. * [x]  #6051 Wrong cell meta removed when deleting rows
1. * [x] #6058 getSourceData functions return wrong data for `nestedRows`
1. * [x] #6066 move multiple rows with `nestedRows`
1. * [x] #6086 Once we enable columnSorting we cannot run the merge() method
1. * [x] #6088 Duplicated rows while using `manualRowMove` with improper index
1. * [x] #6113 We can show columns/row when they're all hidden
1. * [x] #6186 Bug with scrollbar and dimension calculation in Firefox
1. * [x] #6193 Add hooks to collapsibleColumns plugin 
1. * [x] #6167 JSON data with empty value will lose some double quotes when pasted into a cell
1. * [x] #6177 Adjust HiddenRows to new IndexMapper architecture  
1. * [x] #6181 Row selection ignores columns that are hidden at the end
1. * [x] #6204 CollapsibleColumns should no longer use HiddenColumns plugin 
1. * [x] #6218 When we again on the same cell with RMB we get a browser menu 
1. * [x] #6224 Can't hide rows and merge cells at the same time 
1. * [x] #6278 Filters and `minSpareRows` problems at the same time - additional error fixed
1. * [x] #6295 updateSettings can not update tableClassName
1. * [x] #6300 doesn't work with columnSummary when plugin tries to create a row
1. * [x] #6309 Set data at *physical* row instead of visual. **setSourceDataAtCell was added**
1. * [x] #6310 Visual indexes are wrong when using trimRows and columnSorting
1. * [x] #6332 Lost readonly property if I ask confirm in beforeRemoveCol or beforeRemoverow
1. * [x] #6334 Inconsistent selection using the right mouse button for first row/column 
1. * [x] #6346 Missing typings for `instance.undoRedo`
1. * [x] #6347 Typing mismatch for `Handsontable.plugins.ContextMenu`
1. * [x] #6355 We're not able to move column when all columns are selected by ctrl + a 
1. * [x] #6363 minSpareCols with undo adds too many columns
1. * [x] #6371 Some classes for table are missing if one of them is empty
1. * [x] #6376 Hiding rows while there is a merged area involved causes data shifting and 
1. * [x] #6381`walkontable.css` and `handsontable.css` stylesheets are not in sync 
1. * [x] #6386 Wrong selection area after sorting with hidden rows
1. * [x] #6412 After removing column rowHeaders stay improperly
1. * [x] #6413 colHeaders order is not updated after manual move with empty object data source 
1. * [x] #6426 When we define data with more data than used in `columns` we cannot `show column` once it's hidden
1. * [x] #6430 The `afterRowResize` hook shares unbelievable results in the 2nd parameter 
1. * [x] #6432 Can't detach from parent
1. * [x] #6433 Undoing removing nested row doesn't work
1. * [x] #6435 Manual row resize handler throws an error when bottom rows overlay is enabled 
1. * [x] #6463 colHeader is truncated after moving hiddenColumn
1. * [x] #6477 customBorders plugin is missing in the definition file
1. * [x] #6514 PreventOverflow feature doesn't work if multiColumnSorting plugin is enabled 
1. * [x] #6539 beforeRowMove args have wrong types
1. * [x] #6548 `getByRange` for sourceData doesn't work properly with nested object data.
1. * [x] #6557 Hidden (last) column is visible upon resizing Columns
1. * [x] #6559 readOnly for column is erased (does not apply) if we use filters 
1. * [x] #6575 Old CSS classes are not removed after updateSettings
1. * [x] #6595 [8.0.0] Hidden Indexes refactor 
1. * [x] #6600 We're not able to align cells if the selection is made upward
1. * [x] #6664 Add modifySourceData hook and setSourceDataAtRowProp, setSourceDataAtCell methods 
1. * [x] #6668 Column hiding issue after columns moved manually
1. * [x] #6670 Headers are deselected after undoing removing
1. * [x] #6672 Remove `debug` key (key, css, docs)
1. * [x] #6695 columnSummary, Filters and spare rows are causing 'RangeError: Maximum call stack size exceeded'
1. * [x] #6699 [5.0.2] EDGE Dropdown menu onMouseOut event causes critical errors when hovering over vertical scrollbar
1. * [x] #6703 The cell meta is being retrieved using the wrong coordinates 
1. * [x] #6755 Double click on the column resize handle does not adjust size correctly 
1. * [x] #6756 After enabling false to `beforeAutofill` we should add an additional test. 
1. * [x] #6770 Selection skips the highest parent
1. * [x] #6792 Remove old warning 
1. * [x] #6831 Incorrect selection after hiding first row
1. * [x] #6840 Wrong union type for `startPosition`
1. * [x] #6842 Backspace in filter by value option does not work initially
1. * [x] #6843 Calling updateSettings changes the index of frozen columns via freezeColumn method
1. * [x] #6881 Bug: Nested headers and hidden columns highlight the next column
1. * [x] #6888 The wrong data in merge cells after the hidden column and additionally an error occurs.
1. * [x] #6904 trimRows and hiddenRows with certain settings break borders
1. * [x] #6928 nestedRows blocks table from loading if data is not provided
1. * [x] #6965 After moving row from bottom to top the row indexes changes if the first row is hiding.  
1. * [x] #6973 Keyboard navigation with selection does not work on merged cells 
1. * [x] #6974  It’s possible to select hidden column/row. 
1. * [x] #6975 Cannot selectAll when the first row is hidden 
1. * [x] #6976 Hiding first row causes column headers selection to lack blue highlight
1. * [x] #6977 Hiding first row causes 2nd row to lack a top border
1. * [x] #6978 Incorrect column header highlight when merged cells are unmerged and hiddenColumns are used
1. * [x] #6982 [7.0.0] The editor is moved by 1px when the first row / column is hidden
1. * [x] #6990 ReadOnly state for some cells is lost when we remove rows with trimRows turned on
1. * [x] #6992 Undoing column removal causes column headers to lack a header
1. * [x] #7005 We cannot set focus to a column to open context menu after applying a filter 
1. * [x] #7020 mergedCells with hidden causes issues with rendering
1. * [x] #7022 Remove GanttChart plugin 
1. * [x] #7023 Deprecate HeaderTooltips plugin 
1. * [x] #7028 [1.18.0] Too many layers of highlight with noncontinuous selection on merged cells
1. * [x] #7035 NestedHeaders does not allow to define header level as an empty array
1. * [x] #7036 Passing nestedHeaders as a single empty array stops the table from painting
1. * [x] #7043 When we copy and paste a header we get a new empty row when data is hidden
1. * [x] #7045 afterSelectionEnd returns incorrect data when clicking on a column when we have all the rows hidden
1. * [x] #7050 Opening a context menu for a column when its hidden data is selected does not block adding of rows via menu 
1. * [x] #7061 Problems with adding rows from the corner when all rows are trimmed 
1. * [x] #7074 The row/column resize hooks should not return `null`. 
1. * [x] #7076 [2.0.0] Loss of selection after merging from headers 
1. * [x] #7095 We are not able to unmerge cells if part of it is hidden
1. * [x] #7097 Clear() method does not work for hidden data
1. * [x] #7099 calling clear() method removes the focus from the table
1. * [x] #7114 Using read-only and alignment from the context menu when all columns are selected is disabled
1. * [x] #6232 trimWhitespace=false and wordWrapping 
1. * [x] #7103 Additional, native for macOS editor selection in Firefox 78 
1. * [x] #6955 Safari draws different borders than Chrome and FF, when editor is opened
1. * [x] #6788 "Hide" property missing in CustomBorders typings 
1. * [x] #6869 Undo: Add support for fixing columns
1. * [x]  #6149 Rows cannot be resized to less than rowHeights

#### TODO

* [ ] #7031 Methods `colToProp` and `propToCol` should work properly 
* [x] https://github.com/handsontable/angular-handsontable/issues/197  Update Angular wrapper to support v8
* [x] https://github.com/handsontable/vue-handsontable-official/issues/165  Update Vue wrapper to support v8
* [x] https://github.com/handsontable/react-handsontable/issues/189 Update React wrapper to support v8

#### Issues that will NOT be fixed by v8
* ~#4631 Broken height header when use column height and hidden column setting~
* ~#3919 `nestedRows` should work with `ColumnSorting`~
* ~#5525 afterRemoveRow, afterInserRow, afterRemoveCol, afterInsertCol are called before cellMeta is updated~
* ~#5856`nestedRows` should work with `moveRow`~
* ~#6905 We cannot auto fill using db-click if hiddenRows is used~
* ~#6001 Freezing columns do not work with nestedHeaders~
* ~#5125 AutoFill not works will there is a mergedCell in the target area~
* ~#6794 When nestedHeaders are enabled wrong column is removed~
* ~#6787 nestedHeaders blocks rendering of rows if the first row exceeds the viewport~
* ~#6669 Undoing removing hidden rows makes rows exposed~
* ~#5543 Error after update settings rendering twice and picking wrong renderer functions~
* ~#6004 ManualColumnMove dragging breaks after updateSettings()~
* ~#6934 Trimming rows causes the newly added rows by paste to remain~
* ~#6327 Inconsistency with context menu 'Remove columns' option~ 
* ~#1501 Sorting passing logical index through afterChange event~ 
* ~#6728 Copy doesn't work when selected hidden column~ 
* ~#6742 Paste off-by-one after show/hide column~ 
* ~#6743 Too many values pasted when column is hidden~ 
* ~#6833 skipColumnOnPaste and skipRowOnPaste when added to table settings hang the browser down after pasting~
* ~#5961 Additional row added during copy/paste operations and with hidden rows/columns enabled~
* ~#6395 Some headers are gone if we hide and show them again~
* ~#6397 Sorting indicator moves incorrectly when adding a column~ 
* ~#6518 [8.0.0] Moving data isn't working properly, when there are skipped indexes~
* ~#6067 [7.1.0.+] We cannot move nested row to become the last one in the table (related to #6518 ?)~
* ~#7062 Idea of highlighting trimmed headers with blue color (active header)~ 
* ~#6832  Second column selection is misaligned 2 px right~ 
* ~#6960 When there's only one row of data clicking on a header shortens selection by 1px~

**Comment by wojciechczerniak** [comment]
New screenshot
https://github.com/krzysztofspilka/handsontable/blob/master/handsontable-github-preview.png

New logo
https://github.com/krzysztofspilka/handsontable/blob/master/handsontable-logo.svg

**Comment by AMBudnik** [comment]
@wojciechczerniak #5792 is described as
> Issues that may be fixed by #6204

but it is already fixed by this PR https://github.com/handsontable/handsontable/pull/6716 (demo posted https://github.com/handsontable/handsontable/issues/5792)

**Comment by wojciechczerniak** [comment]
After beta.2 there are more issues that are connected to the changes we've made:

- [x] #5208 Filtering results in blank rows 
- [ ] #5125 AutoFill not works will there is a mergedCell in the target area 
- [ ] #5999 handsontable 7.0.2 context menu issue with multiple selected rows in case of 1st column hidden 
- [ ] #6051 Wrong cell meta removed when deleting rows 
- [ ] #6381`walkontable.css` and `handsontable.css` stylesheets are not in sync 
- [ ] #6397 Sorting indicator moves incorrectly when adding a column 
- [ ] #6413 colHeaders order is not updated after manual move with empty object data source 
- [ ] #6669 Undoing removing hidden rows makes rows exposed 
- [ ] #6743 Too many values pasted when column is hidden 
- [ ] #6742 Paste off-by-one after show/hide column 
- [ ] #6728 Copy doesn't work when selected hidden column 
- [ ] #6703 [8.0.0] The cell meta is being retrieved using the wrong coordinates 
- [ ] #6833 skipColumnOnPaste and skipRowOnPaste when added to table settings hang the browser down after pasting 
- [ ] #6794 When nestedHeaders are enabled wrong column is removed 
- [ ] #6934 Trimming rows causes the newly added rows by paste to remain 
- [ ] #6965 After moving row from bottom to top the row indexes changes if the first row is hiding.  
- [ ] #6787 nestedHeaders blocks rendering of rows if the first row exceeds the viewport 
- [ ] #6518 [8.0.0] Moving data isn't working properly, when there are skipped indexes 
- [ ] #6004 ManualColumnMove dragging breaks after updateSettings() 
- [ ] #6001 Freezing columns do not work with nestedHeaders 
- [ ] #5525 afterRemoveRow, afterInserRow, afterRemoveCol, afterInsertCol are called before cellMeta is updated 
- [ ] #5543 Error after update settings rendering twice and picking wrong renderer functions 
- [ ] #5792 BUG: Expand collapsed column, is expanding also 'child' collapsed columns, except the first child 

---
- [ ] #6309 Set data at *physical* row instead of visual. **setSourceDataAtCell was added**

**Comment by AMBudnik** [comment]
Epic closed with the release of v8.0.0
