### ISSUE TITLE
New formula plugin

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6466]
### Description
Create a completely new formula plugin that will be based on the HyperFormula engine.

This is an Epic. Work should be split into smaller tasks.

### Requirements
- [x] Create new branch `feature/hyperformula-plugin`
- [x] Use v8.0.0 branch for the development
- [x] Should be written in ES6
- [x] Create a plugin skeleton that is based on our current formula plugin
- [x] Copy e2e tests: src/plugins/formulas/test/formulas.e2e.js
- [ ] Finished engine API handsontable/hyperformula#1
- [ ] Run the tests with the new engine and report all the differences
- [ ] Do a performance tests for current and new plugin version
- [ ] Add missing tests for: `mergeCells`, `hiddenColumns`, `hiddenRows`, `collapsibleColumns`, `nestedRows`, `filters`, `trimRows`
- [ ] Should fix most of the bugs that were reported for previous formula engine: https://github.com/handsontable/handsontable/labels/Formulas
- [ ] Should work seamlessly with `trimRows`, `filters` and `nestedRows`. When rows are trimmed we need to keep rows and headers they should keep their numbers so formulas are relevant to headers. We can use `bindRowsWithHeaders` or create a custom solution. 
- [ ] `Filters` and `search` should receive calculated value instead of formula.
- [ ] Support for multiple worksheets
    - [ ] Initialize Handsontable even when HF sheet already exists, use it
    - [ ] Hold the recalculation until all HoT instances are initialized
    - [ ] Some HoT instances can be destroyed, calculation should work anyway
- [ ] Add `beforeValidate` hook to check for circular reference
- [ ] Nested rows should return correct flat getSourceData to provide correct data struture to HyperFormula
- [ ] Propose alternative to variables or add support for them
- [ ] Should have an API to calculate a custom formula
- [ ] Plugin should dispatch a new hook on formula change and when values are updated
- [ ] HyperFormula instance sharing should be opt-in
- [x] ~Should re-export enums from HyperFormula engine?~ No. Import from HyperFormula
- [x] ~Should re-export everything that is required to create custom formulas~ Same as above
- [x] ~Create new settings key for HypeFormula plugin called... `hyperformula` 🎉  This way we can keep both plugins and there will be less work with backward compatibility.~ Probably no.

### Tasks

- [x] #6664 Add `modifySourceData` hook for `set` and `get` io modes
- [x] #6664 Add `setSourceDataAtCell` public method
- [x] #6664 Add `setSourceDataAtRow` public method
- [ ] #6772 Integrate CRUD operations with HOT 
- [ ] Add API for registering new custom formulas
- [ ] Add API for registering new languages and switching sheet language
- [ ] Add undo and redo support. Use HF API
- [ ] #6767 Add copy and paste support. Use HF API https://github.com/handsontable/hyperformula/issues/74
- [ ] #6769 Add new keyboard shortcut to switch between values and formulas display modes. We can check the flag in `onModifyData` hook and use different HyperFormula method accordingly. The shortcut for Windows is CTRL + ` (grave accent, whatever it is).
- [ ] Keep rows and columns headers in sync with formulas (when trimmed/filtered, row IDs should be hidden as well, bindHeadersWithRows or something like that)
- [ ] Initializing multople HOT instances with the same HF instance, multiple workseets support
- [ ] Destroy HF instance when no longer used with `engine.destroy()` method. Caution: other HOT instances may use the HF instance
- [ ] UpdateSettings should call HF.updateConfig
- [ ] Add `beforeValidate` hook to check for circular reference
- [ ] #6768 Expose HF helpers: `calculateFormula`, `validateFormula`, `normalizeFormula`
- [ ] #6771 Add API for `namedExpressions`
- [ ] What is not re-exported will be available through `getPlugin().hyperFormula` getter
- [ ] Add `formulaUpdated` hook, when references are recalculated. Use HF event https://github.com/handsontable/hyperformula/issues/24
- [ ] Trigger `afterChange` when HF changes value (with source 'formula'). Use HF event https://github.com/handsontable/hyperformula/issues/24
- [ ] Update Typescript definition file for the plugin APIs
- [ ] HF requires a licenseKey, use "internal-use-in-handsontable"
- [ ] Formula Editor #75
- [ ] ~Create formula editor with point and click interface~ Not a part of this epic

### HyperFormula instance should be opt-in

Maybe something like this?

```ts
const hotInstanceOne = new Handsontable();

const hotInstanceTwo = new Handsontable({
    formulas: {
        hyperFormulaInstance: hotInstanceOne,
    }
});
```

### Issues

- [x] #3908 IF condition formula seems not to evaluated when enter new value
- [ ] #4066 Formula does not get initially evaluated with column mapping - **still broken**
- [x] #4154 formulas not init with nestedRows
- [x] #4353 When the cell type is numeric, the formula does not work properly.
- [x] #4357 Circular reference error in the formula
- [x] #4430 Formulas does not apply for some cells
- [x] #4654 After inserting a row, an auto-updated formula displays incorrect value
- [ ] #4668 Formulas do not recalculate when we move columns - `blocked` by https://github.com/handsontable/handsontable/issues/8114
- [x] #4675 AVERAGE formula updates incorrectly
- [ ] #4678 Formulas recalculates when we block a change via beforeChange - `blocked` by https://github.com/handsontable/handsontable/issues/8107
- [x] #4693 Handsontable should work without formula parser enabled
- [x] #5279 Bug in formula parsing when using nested data structures.
- [ ] #5455 Column with formulas doesn't filter properly - **still broken**
- [x] #5550 after remove columns get wrong sourceData with formulas enabled
- [x] #5613 continus removeRow cause error in formula situation
- [x] #5635 Formulas don't update after row is removed
- [ ] #5689 beforeChange event i cahnge a value, but the relate formula calculate wrong - **still broken**
- [x] #5870 Calculation issue when IF is used on FALSE data
- [x] #5872 AVERAGE doesn't allow to define numbers as strings
- [x] #6248  Using clear() method breaks down formulas 
- [x] #6336  Formulas are incorrectly calculated / auto updated on sort 
- [ ] #6359  Formula is converted to a value if merged areas are included - **still broken, out of scope**
- [x] #6480 It seems that the Formulas plugin doesn't work well with sorting. 
- [x] #6751 When formulas are enabled we cannot change metadata in the cells method
- [ ] #6932 Formulas do not calculate if they're used as new values in the beforeChange hook - **still broken**

### API
Pseudo code proposition. Not a final version.

```ts
// Language support
public registerLanguage(languageName: string, languageSet: LangDefinition) {
  this.hyperformula.registerLanguage(languageName, languageSet);
}

public setLanguage(languageName: string) {
  this.hyperformula.setLanguage(languageName);
}

// Callback or Class? Define the FunctionPlugin format and options / meta format
public registerFormula(name: string, callback: function, options = {}) {
  this.hyperformula.registerFormula(name, callback, options);
}

// Renderer will request the value
public getCellValue(row: number, column: number, sheet: number = this.sheet): HyperFormula.CellValue {
  return this.hyperformula.getCellValue({ sheet, row, column });
}

// Editor will request the formula
public getCellFormula(row: number, column: number, sheet: number = this.sheet): string {
  return this.hyperformula.getCellFormula({ sheet, row, column });
}

public hasCellValue(row: number, column: number, sheet: number = this.sheet): boolean {
  return this.hyperformula.hasCellValue({ sheet, row, column });
}

public hasCellFormula(row: number, column: number, sheet: number = this.sheet): boolean {
  return this.hyperformula.hasCellFormula({ sheet, row, column });
}

// Helpers moved to #6768 

// Only recalculate on request. Don't rerender yet.
public recalculate(): void {
  const changes = this.hyperformula.recalculate();

  this.markChangedCellsAsDirty(changes);
}

public destroy(): void {
   this.hyperformula.destroy(); // but ONLY when no other instance is using it
}

// Current Handsontable instance is a worksheet, should have some kind of ID
private get sheet(): string {
  return this.hot.getSettings().formulas.sheetID;
}

private get config(): HyperFormula.Config {
  return new HyperFormula.Config({
    ...
  });
}

// one HyperFormula per page? We can identify Handsontable as a sheet by ID
// or HyperFormula instance should be created outside of HoT and set by reference
private get hyperFormula(): HyperFormula {
  if (!privatePool.hyperformula) {
    privatePool.hyperformula = new HyperFormula(this.config);
  }

  return privatePool.hyperformula;
}

// CRUD operations moved to #6772

// We need to load data to the right worksheet
private onAfterLoadData() {
  if (this.hyperformula.isItPossibleToAddSheet(this.sheet)) {
    this.hyperformula.addSheet(this.sheet);
  }

  const simpleAddress = { col: 0, row: 0, sheet: this.sheet };
  const data = this.hot.getData();

  this.hyperformula.setMultipleCellContents(simpleAddress, data);

  this.recalculate();
}

// Modify value that will be rendered, copied or exported to CSV
private onModifyData(row, column, valueHolder, ioMode) {
  if (ioMode === 'get') {
    valueHolder.value = this.hyperformula.getCellValue(row, column);
  } else if (ioMode === 'set' && this.hyperformula.isItPossibleToChangeContent()) {
    valueHolder.value = this.hyperformula.normalizeFormula(valueHolder.value);
  }
}

// Modify value for editor / formula bar
private onModifySourceData(row, column, valueHolder, ioMode) {
  if (ioMode === 'get') {
    valueHolder.value = this.hyperformula.getCellFormula(row, column);
  } else if (ioMode === 'set' && this.hyperformula.isItPossibleToChangeContent()) {
    valueHolder.value = this.hyperformula.setCellContent(valueHolder.value);
  }
}

// An event that listens (and is triggered) on HyperFormula engine
private onValueUpdated(changes: CellValueChange[], sourceSheet: string) {
  if (this.sheet !== sourceSheet) {
    this.markChangedCellsAsDirty(changes);
    this.hot.render();
  }
}

// An event that listens (and is triggered) on HyperFormula engine
private onFormulaUpdated() {
  // update sourceData? or opened editor? or formula bar? etc.
}
```

**Comment by wojciechczerniak** [comment]
> In manual calculation mode, you can trigger this smart recalculation by pressing F9. You can force a full calculation of all the formulas by pressing Ctrl+Alt+F9, or you can force a complete rebuild of the dependencies and a full calculation by pressing Shift+Ctrl+Alt+F9.

It might be useful to implement additional shortcuts. But we will need additional public API methods. `recalculate()`, `fullRecalculate()` or `recalculate(full = true)`, `rebuildAndRecalculate()` ?

**Comment by AMBudnik** [comment]
Adding newer issues to the main list

1. - [ ] https://github.com/handsontable/handsontable/issues/6790 - SUMIF formula does not allow to use strings in conditions
2. - [ ] https://github.com/handsontable/handsontable/issues/7041 - Wrong formula value after double-clicking dependent cell
3. - [ ] https://github.com/handsontable/handsontable/issues/7072 - SUMIF support for optional sum_range
4. - [ ] https://github.com/handsontable/handsontable/issues/7178 - Can I create a custom function

**Comment by AMBudnik** [comment]
For everyone tracking this epic, I would just like to inform you that this epic is a source of issues for the Formula Plugin using the HyperFormula engine. But the actual progress of the task is tracked and scheduled under Github projects available at https://github.com/handsontable/handsontable/projects/2

**Comment by amaidah** [comment]
> For everyone tracking this epic, I would just like to inform you that this epic is a source of issues for the Formula Plugin using the HyperFormula engine. But the actual progress of the task is tracked and scheduled under Github projects available at https://github.com/handsontable/handsontable/projects/2

Thank you for the transparency, I see this epic has been open since 2019, any ideas on when we might see this land? Being able to create custom functions for handsontable would be killer

**Comment by AMBudnik** [comment]
@amaidah the deadline is a bit loose - we surely would like to push a version before the end of the year.

**Comment by AMBudnik** [comment]
Hi @amaidah 

If you haven't checked the new Handsontable v9.0.0 with the new formula plugin powered by HyperFormula engine I highly encourage you to give it a try.

We have fixed many issues with the new formula.

ps. here are the release notes https://handsontable.com/docs/8.2.0/tutorial-release-notes.html

**Comment by AMBudnik** [comment]
We can call this epic completed with the release of Handsontable v9.0.0
Further development on the Formula plugin will be converted in new issues.

**Comment by amaidah** [comment]
> Hi @amaidah
> 
> If you haven't checked the new Handsontable v9.0.0 with the new formula plugin powered by HyperFormula engine I highly encourage you to give it a try.
> 
> We have fixed many issues with the new formula.
> 
> ps. here are the release notes https://handsontable.com/docs/9.0.0/tutorial-release-notes.html

Awesome! Congratulations, looks like this was finished earlier than expected. However I don't see, in this epic tracker, the ability to write custom formulas/function yet. Am I reading this accurately?

**Comment by AMBudnik** [comment]
Hi @amaidah 

Here are the docs on how to add a custom function https://handsontable.github.io/hyperformula/guide/custom-functions.html#translations and here  https://codesandbox.io/s/broken-paper-pdpbb is an example with a custom function already added.

Let me now know if you'd need anything more than that.

**Comment by amaidah** [comment]
> Hi @amaidah
> 
> Here are the docs on how to add a custom function https://handsontable.github.io/hyperformula/guide/custom-functions.html#translations and here https://codesandbox.io/s/broken-paper-pdpbb is an example with a custom function already added.
> 
> Let me now know if you'd need anything more than that.

Thank you for the quick reply. So by adding a custom formula to HyperFormula, we would be able to use that in Handsontable?

I was specifically asking about this unmarked task:
![image](https://user-images.githubusercontent.com/16659483/121722698-7c0e0500-ca9a-11eb-8bc4-a1cacf07c2cd.png)

**Comment by AMBudnik** [comment]
Hi @amaidah 

yes, you can test it under this demo https://codesandbox.io/s/zen-heisenberg-vgfli 

The `HYPER` function is a new registered formula. What it does is multiply the passed numeric value by `400`. It can be tested within the first cell in the Handsontable table. The _index.js_ file (where the Handsontable instance is declared) imports the _hs.js_ logic when the new formula is described and registered.
