### ISSUE TITLE
Refactor custom borders to use SVGs insead of DIVs

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6467]
### Description
Refactor DIV based border renderer to SVG one. The main reason behind this change is the performance of Handsontable instance with multiple cell borders. As a side effect, we've fixed few long standing issues with custom borders.

Oh, and they are now beautiful:
![obraz](https://user-images.githubusercontent.com/4718998/68804479-18271e80-0662-11ea-9f17-f6128ff5aac6.png)

This was huge and the results are amazing. Multiple tests were added.

Epic. Work was done within smaller issues.

### To Do

- [ ] New documentation for SVG borders, including styling
- [ ] Migration guide from DIV borders to SVG ones, including styling/printing
- [ ] Document all the breaking changes for release notes and blog post

### Related issues
We should check those

- [x] #6064 Custom borders create many elements and operations in DOM
- [x] #6052 Custom borders plugin hook calls grow exponentially with data size
- [ ] #4142 Custom border on fixed row 
- [ ] #4859 Merged Cells + selection causes improper merge cell highlight. 
- [ ] #4940 The selection doesn't work with merged cells with fixed overlays 
- [ ] #4993 The fragmentSelection doesn't draw all the borders in some cases 
- [ ] #5245 More custom border styles 
- [ ] #5298 Printing custom borders
- [ ] #5568 CustomBorders draws borders of width 2px+ incorrectly 
- [ ] #6063 Borders after insert row are not movedown  (probably cellMeta #6274)
- [ ] #6453 Border priority of borders of the same size 

### Checklist

- [ ] Various widths: 1px, 2px, ..., 5px?
- [ ] Various colours
- [ ] Various combinations, thick with thin, vertical, horizontal
- [ ] Is it possible to print the border?
- [ ] Border spanned across rows / columns
- [ ] Each cell border different
- [ ] Put the performance at test, create as many borders as possible
- [ ] Creating/removing borders from context menu
- [ ] Creating/removing borders from API
- [ ] How does it work with `updateSettings`?
- [ ] Can we change the styles with CSS?

**Comment by wojciechczerniak** [comment]
It should be easier to test the feature/PR with this related issue list and checklist @aninde. If you have anything to add/remove feel free.

CC @AMBudnik

**Comment by AMBudnik** [comment]
I would also add 

* resizing associated cells (+dbclick - quick resize)
* undo/redo after scrolling /filtering /moving / resizing
* in window scenarios (iframe)

and remember to check all the browsers and go locally ;)

**Comment by aninde** [comment]
@wojciechczerniak @AMBudnik thank you very much for preparing the checklist. Also, I would like to check custom borders with:

- overlapping customBorders
- intersection customBorders
- fixed/frozen rows/columns
- contextMenu
- dropdownMenu - expanded dropdown list
- autofill 
- various overlays - top, left and all
- nested rows and headers
- collapsible columns
- IME (Internationalization)
- on iPad & on mobile

**Comment by aninde** [comment]
Due to better readability i will report bugs related to `svg` branch here, not in PR.
During testing, I use Mac Magic Mouse with the ability to vertical and horizontal scrolling or laptop's trackpad with the same feature. 
I don't click on the scrollbar, I don't want to lost focus on selection. 

### Case 1 
**Jumping selection** https://github.com/handsontable/handsontable/pull/6157#issuecomment-559401554

### Case 2 
Chrome, Safari, Firefox / MacOs Pro, Regression.
Use the same setting as in demo https://jsfiddle.net/aninde/f30rjd6u/
![cut fillhandle Firefox](https://user-images.githubusercontent.com/30186818/69796056-9ab8ed80-11cd-11ea-9ee5-d6eb749dd494.gif)

**Steps to reproduction**
1. Select fixed column B.
2. Set viewport to be narrow to see horizontal and vertical scroll.
3. Scroll it horizontally.

**Result** Notice that the blue square of fileHandle is rectangle, not square and is cutted while scrolling
**Expected result** Should work as in `7.2.2`. Should be square and stay with border of fixed column during scrolling. 

### Case 3 
**Overlaying right border on fixedColumnsLeft/frozen columns**.
Occurs on Chrome, Firefox, Opera, Microsoft Dev Edge / MacOs and very fast on safari, so it's hard to notice. 

**SVG Branch - Firefox 70, locally**
![left-border-ff-svg](https://user-images.githubusercontent.com/30186818/69795978-6f360300-11cd-11ea-9cc4-1f1ca0e9f8ee.gif)

**7.2.2 Firefox, jsfiddle**
![selection7 2 2](https://user-images.githubusercontent.com/30186818/69799077-defabc80-11d2-11ea-9da8-cbdbcec21563.gif)

**Steps to reproduction**
1. Set viewport to be narrow to see horizontal and vertical scroll.
2. Select one cell from column C, maybe C11.
3. Scroll it horizontally with changed speed to the right and back to the left the faster when you are close to the end of the left margin of the site. 

**Result:** Pink, the right border is overlaying fixed columns. Selection is doubled and moved. 
**Expected result:** Fixed/frozen columns should be on top.

### Case 4 
**Only fixedRowsTop, overlaying top border while scrolling with fixedRowsTop**

It works worst in the Firefox, but even in Chrome and Safari doesn't look good. 
1. Comment fixedColumnsLeft, uncomment fixedRowsTow in settings.
2. Scroll it with a trackpad, without clicking to change focus. 
3. The result is similar to the bug connected to `fixedColumnsLeft/frozen columns`.

**Firefox SVG Branch**
![fixedrowstop-ff-svg](https://user-images.githubusercontent.com/30186818/69797142-7fe77880-11cf-11ea-8964-f453f1648e81.gif)

**Chrome SVG Branch**
![fixedrowsTop-chrome-svg](https://user-images.githubusercontent.com/30186818/69797138-7d851e80-11cf-11ea-9fb3-e69564cb0037.gif)

**Comment by aninde** [comment]
`customBorders` are not rendering in any browser when there is space in color name https://jsfiddle.net/aninde/bfckronw/ `7.2.2 with svg borders`

**Comment by aninde** [comment]
https://github.com/handsontable/handsontable/issues/6453#issuecomment-560371785 the color order is not preserved.

**Comment by aninde** [comment]
I'm not sure about the assumption with zooming and blurriness. On [PR](https://github.com/handsontable/handsontable/pull/6157#issue-301857834) description was:
_The borders should looks sharp in every browser at 100% zoom level. They might be blurry at other zoom levels that are not multiplies of 100._ I'm not sure that we met that assumption. 

I wear glasses so I need someone with healthy eyes to look at it too. @jansiegel @budnix @AMBudnik can you double-check how `selection` and `customBorders` looks on zoom 125%, 150% and 200% on Chrome, Firefox, Safari, IE and Microsoft Edge? 
https://jsfiddle.net/aninde/6c2znt15/2/


Below, I paste print screens on the 150% zoom in and zoom into those print to see details. 
Sadly the blurriness is worse on Windows. Here is example from `Edge.`
![Screenshot 2019-12-02 at 15 49 27](https://user-images.githubusercontent.com/30186818/69968766-60c45000-151b-11ea-9b46-85e7358af318.png)

`Chrome/Mac OS` 150% zoom
![chrome-150-svg](https://user-images.githubusercontent.com/30186818/69967559-f3172480-1518-11ea-8af7-4cfdb76b42ba.png)
![Screenshot 2019-12-02 at 15 07 31](https://user-images.githubusercontent.com/30186818/69968041-e6470080-1519-11ea-8967-4faaf0997cb0.png)


![chrome-150-latest](https://user-images.githubusercontent.com/30186818/69967562-f4e0e800-1518-11ea-9031-e022575c9521.png)
![Screenshot 2019-12-02 at 15 07 03](https://user-images.githubusercontent.com/30186818/69968023-db8c6b80-1519-11ea-869f-46e2f9defa8a.png)

**Comment by jansiegel** [comment]
@aninde 
> The borders should looks sharp in every browser at 100% zoom level. They might be blurry at other zoom levels that are not multiplies of 100.

> can you double-check how selection and customBorders looks on zoom 125%, 150% and 200% on Chrome, Firefox, Safari, IE and Microsoft Edge?

They look sharp at multiplies of 100, and a little blurry on other levels, just as @warpech stated in #6157, at least on Chrome, Firefox and Safari.

**Comment by aninde** [comment]
### Summary of testing 

Found: 

- [ ] https://github.com/handsontable/handsontable/issues/6467#issuecomment-559440649
- [ ] https://github.com/handsontable/handsontable/issues/6467#issuecomment-560370346
- [ ] https://github.com/handsontable/handsontable/issues/6467#issuecomment-560372097


Fixed issues that they need to add tests to: 

- [ ]  #4142 Custom border on fixed row 
- [ ] #4940 The selection doesn't work with merged cells with fixed overlays 
- [ ] #5298 Printing custom borders with bootstrap css 
- [ ] #5568 CustomBorders draws borders of width 2px+ incorrectly

**Comment by warpech** [comment]
@krzysztofspilka asked me for estimate how much time is needed to finish. Here are my pessimistic estimates (total: up to 9 days).

> - https://github.com/handsontable/handsontable/pull/6157#issuecomment-559401554 Case 1: Jumping selection
> - https://github.com/handsontable/handsontable/issues/6467#issuecomment-559440649 Case 3: Overlaying right border on frozen columns while scrolling
> - https://github.com/handsontable/handsontable/issues/6467#issuecomment-559440649 Case 4: Overlaying top border on frozen rows while scrolling

These are the occurences of the same problem: There is a race condition between border rendering and overlay positioning when main window serves as a scroll container. Additional problem, that seems to be related: in some Walkontable tests, I must call `Walkontable.draw()` twice to get the desired rendering. Work in progress to fix this is on the branch https://github.com/handsontable/handsontable/commits/feature/issue-6064-touch-overlays, but the further I get, the more I get entangled in quirks of overlay rendering. I might need 2-3 days for this.

> - https://github.com/handsontable/handsontable/issues/6467#issuecomment-559440649 Case 2: Leaking fill handle in overlay

This might take 1 day.

> - https://github.com/handsontable/handsontable/issues/6467#issuecomment-560370346 Case 5: Border colors with spaces

This might take 1 day.

> - https://github.com/handsontable/handsontable/issues/6467#issuecomment-560372097 Case 6: Border color order

This might take 1 day.

> Fixed issues that they need to add tests to:
> 
> - #4142 Custom border on fixed row
> - #4940 The selection doesn't work with merged cells with fixed overlays
> - #5298 Printing custom borders with bootstrap css
> - #5568 CustomBorders draws borders of width 2px+ incorrectly

Can we please move this out of scope of the PR https://github.com/handsontable/handsontable/pull/6157. My rough estimate is that it might take 1 day of work for each test.

**Comment by warpech** [comment]
As said in point 2 of https://github.com/handsontable/handsontable/pull/6157 OP, the `feature/issue-6064` branch removes the only way to restyle borders using CSS. Meaning: it will no longer be possible to set the border colors of current selection, area selection and fill area using CSS (demo: https://jsfiddle.net/kayw7e20/1/).

I am not sure of the severity of this. Was such possibility ever advertised in the docs? Are our customers using it? If yes, then I think we need to add a proper API for selection customization and explain the migration.

@wojciechczerniak, @krzysztofspilka WDYT?

**Comment by aninde** [comment]
@warpech the demo in your comment is in the stable version 7.2.2
![Screenshot 2019-12-16 at 14 43 09](https://user-images.githubusercontent.com/30186818/70911539-64270380-2012-11ea-9e31-c1aaa65429db.png)

This is how selection looks on your PR with changed CSS. Only square is changed. Is this in line with the assumptions?
`7.2.2. v. with svg, 29.11.19 build.` https://jsfiddle.net/aninde/4zkrvqgs/ 
![Screenshot 2019-12-16 at 14 39 15](https://user-images.githubusercontent.com/30186818/70911488-4b1e5280-2012-11ea-9927-53a7a6a05c2a.png)

**Comment by warpech** [comment]
> This is how selection looks on your PR with changed CSS. Only square is changed. Is this in line with the assumptions?

It is in line with my assumptions, yes. I changed the CSS API of the "borders" but did not change the CSS API of the "corners".

**Comment by wojciechczerniak** [comment]
> I am not sure of the severity of this. Was such possibility ever advertised in the docs? Are our customers using it? If yes, then I think we need to add a proper API for selection customization and explain the migration.

It was: https://handsontable.com/docs/1.17.0/tutorial-styling.html and was removed.

I don't have evidence for this, but it might be an important part of the customization process. Everything that is a part of the UI should be customizable in terms of color at least. In #6538 @AMBudnik proposes a feature to keep this feature. I've found one question about it #2487

**Comment by warpech** [comment]
> I don't have evidence for this, but it might be an important part of the customization process. Everything that is a part of the UI should be customizable in terms of color at least.

I made a small PR that implements this: https://github.com/handsontable/handsontable/pull/6593. However there is one pitfall (see in the PR's first comment).

**Comment by warpech** [comment]
I made a big PR that fixes "Case 1", "Case 3" and "Case 4" explained in this issue: https://github.com/handsontable/handsontable/pull/6594

@aninde are you sure that "Case 2" is a regression in the SVG borders branch? I think I can reproduce the same problem with 7.2.2 and 7.3.0.

**Comment by aninde** [comment]
@warpech you are correct. "Case 2" it is not regression, it can be reproduced on 7+ version, my mistake.

**Comment by aninde** [comment]
I found a few bugs that I missed earlier on printouts.
Custom border prints look much better, because before they looked like this
![Screenshot 2020-01-08 at 14 09 41](https://user-images.githubusercontent.com/30186818/71981125-fe4d2680-3221-11ea-8b99-716968d82ee8.png)

Now they looks awesome

![Screenshot 2020-01-08 at 14 20 51](https://user-images.githubusercontent.com/30186818/71981176-191f9b00-3222-11ea-8e0c-83c3dbe2bab4.png)


1. FillHandle does not print on printouts. Selection prints, but fillHandle is missing. 
Do we even want selection to be printed? 
Excel does not print them. IMHO, it should not be visible on the print in Handsontable.
![Screenshot 2020-01-08 at 14 09 31](https://user-images.githubusercontent.com/30186818/71981194-22106c80-3222-11ea-8182-1558206d42a3.png)

2. The bottom border is doubled, it emerges from under the customBorder. This occurs when fixed rows are enabled. 
![Screenshot 2020-01-08 at 14 21 30](https://user-images.githubusercontent.com/30186818/71981432-b4187500-3222-11ea-9ca4-243dd2767426.png)

without fixed rows this bug do not occur. Bottom border of colHeader is also in version 7.3.0, which is why I don't report it here.
![Screenshot 2020-01-08 at 14 25 40](https://user-images.githubusercontent.com/30186818/71981497-d27e7080-3222-11ea-9940-9444f34932fd.png)

**Comment by aninde** [comment]
2. The bottom border is doubled, it emerges from under the customBorder. This occurs when fixed rows are enabled. 
![Screenshot 2020-01-08 at 14 21 30](https://user-images.githubusercontent.com/30186818/71981432-b4187500-3222-11ea-9ca4-243dd2767426.png)

without fixed rows this bug do not occur. Bottom border of colHeader is also in version 7.3.0, which is why I don't report it here.
![Screenshot 2020-01-08 at 14 25 40](https://user-images.githubusercontent.com/30186818/71981497-d27e7080-3222-11ea-9940-9444f34932fd.png)

**Comment by wojciechczerniak** [comment]
>  Excel does not print them. IMHO, it should not be visible on the print in Handsontable.

+1 on that. We should hide the rest of the selection and white rectangle that covers the grid.

But it's out of the scope so up to you.

**Comment by warpech** [comment]
Keep in mind that the problem still exists that we cannot set custom styles for area selection, until the area selection was used. It is explained in more details in https://github.com/handsontable/handsontable/pull/6593#issue-358600499 (OP and the first comment by @aninde).

**Comment by warpech** [comment]
I closed the SVG borders PR https://github.com/handsontable/handsontable/pull/6157, becuase it got largely outdated. At some point, we will reimplement this on a fresh branch.

**Comment by warpech** [comment]
I closed the SVG borders PR https://github.com/handsontable/handsontable/pull/6157, becuase it got largely outdated. At some point, we will reimplement this on a fresh branch.

**Comment by warpech** [comment]
I closed the SVG borders PR https://github.com/handsontable/handsontable/pull/6157, becuase it got largely outdated. At some point, we will reimplement this on a fresh branch.

**Comment by adrianszymanski89** [comment]
Inform [ZD](https://handsontable.zendesk.com/agent/tickets/28873)

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/pull/6157. We should rather discuss that internally if there's any need and improvement to choose this approach with the current structure of Handsontable.
