### ISSUE TITLE
[8.0.0] Hidden Indexes refactor

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6595]
### Description

Refactor hidden columns and rows to use `indexMapper` introduced in #5751. HiddenColumns, HiddenRows, and CollapsibleColumns should register their `hiddenMaps` so they will work correctly with CRUD operations

### Epic is split into smaller tasks

- [ ] #6178 Extend `indexMapper` with `hiddenCollection`
- [ ] #6178 `hiddenColumns` plugin refactor to use IndexMapper
- [ ] #6204 Remove the connection between collapsibleColumns and hiddenColumns plugins
- [x] #6177 `hiddenRows` plugin refactor to use IndexMapper

### Breaking changes

- TD/TH elements of hidden columns and rows are not created in DOM anymore
-  Removing `hiddenRow` and `hiddenColumn` hooks. We can make it backward compatible but then we have to move this hook to `indexMapper` and his `isHidden` or place it in core. Otherwise each plugin that uses `hiddenCollection` will have to add its own handler. Meh.
- Removing `onBeforeSetRangeStart` and `onBeforeSetRangeEnd` hooks. It's used by `mergeCells` plugin. Not sure if we can remove it. We can make it backward compatible if we use it to alter the selection in the core where we have access to index mapper instead of registering multiple hooks in every plugin.
- Not storing `skipRowOnPaste` and `skipColumnOnPaste` in cell meta. It will not be possible for the developer to set those properties and get a similar effect.
- If we remove `onAfterGetCellMeta` what will happen to `afterHiddenColumn`, `firstVisibleColumn`, `afterHiddenRow`, `firstVisibleRow` CSS classes?
- If we remove `onAfterGetCellMeta` handler from plugins `skipColumnOnPaste` and `skipRowOnPaste` will no longer be set on cell meta. It can't be altered through cell meta and should be migrated.
- The class `afterHiddenRow` will not be used anymore?
- You will not be able to set `skipRowOnPaste` on a single cell? It's a row property anyway.

### API and backward compatibility

- [x] `Core.getCell()` should return `null` for hidden columns/rows. This works according to docs, only rendered elements are returned. Might be considered a breaking change but is already mentioned in breaking changes. We can mention it, just to be sure.
- [x] `Core.getColHeader()` should support hidden columns
- [ ] `Core.getColWidth()` should return `0.1` for hidden columns. Backward compatible.
- [ ] `Core.getSelected*()` should return indexes of selected cell ranges, including hidden columns
- [ ] `getColHeader` hook should not be called for hidden columns.
- [ ] Public methods `Core.toPhysical()` and `Core.toVisual()` should not change. Breaking change is unnecessary here ATM, external developer does not need `renderable` indexes. They are for Walkontable only.

### Related issues

- [x] #4121 Hidden columns become visible when we run updateSettings
- [x] #4181 using 'hiddenColumns' and 'stretchH' shows a unnecessary horizontal scrollbar when there is enough space
- [x] #4370 If the last column is a hidden column and stretchH is enabled, last column is being displayed
- [x] #4381 `updateSettings` performance is very low because of `hiddenColumns`
- ~~[ ] #4631 Broken height header when use column height and hidden column setting~~
- [x] #4716 Collapse not working correctly when using custom cell rendrers
- [x] #5015 [1.8.2+] Incorrect header name
- [x] #5571 `hiddenColumns` doesn't work with `columnSorting`
- [x] #5588 autoRowSize renders wrong height after hiding column
- [x] #5598 [8.0.0.-rc1] `manualColumnMove` should work with `hiddenColumns`
- [x] #5704 hiddenColumns option interferes with keyboard movement.
- [x] #5771 getSourceData functions return wrong data for nested rows
- [x] #5817 Hiding first rows bug
- [x] #5847 Missing border left/top when use hiddenColumns/hiddenRows.
- ~~[ ] #5864 Make collapse/expand plugin in nested header configurable~~
- [x] #5871 Hiding columns affect selection of hidden columns
- [x] #5875 `collapsibleColumns` should work without `hiddenColumns`
- [x] #5877 hiddenRows/hiddenColumns doesn't work properly with autoWrapRow/autoWrapCol
- [x] #5871 Hiding columns affect selection of hidden columns
- [x] #5881 When we hide first column on IE we get double border for top left corner
- [x] #5882 Indexes of nestedHeaders are not recalculating after remove/add column
- [x] #5883 `hiddenColumns` plugin unsets cell's `renderer`
- [x] #5909 `hiddenColumns` stores visual indexes, should use physical
- ~~[ ] #5961 Additional row added during copy/paste operations and with hidden rows/columns enabled~~
- [x] #6113 We can show row/columns when they're all hidden
- [x] #6181 Row selection ignores columns that are hidden at the end
- [x] #6204 CollapsibleColumns should no longer use HiddenColumns plugin
- [x] #6224 Can't hide rows and merge cells at the same time
- [x] #6426 When we define data with more data than used in `columns` we cannot `show column` once it's hidden
- [x] #6376 Hiding rows while there is a merged area involved causes data shifting and unexpected merged area coordinates
- [x] #6386 Wrong selection area after sorting with hidden rows
- ~~[ ] #6395 Some headers are gone if we hide and show them again~~
- [x] #6463 [8.0.0-beta.1] colHeader is truncated after moving hiddenColumn
- [x] #6557 Hidden (last) column is visible upon resizing Columns
- [x] #6641 with hidden column, collapsibleColumns don't work well 

### Tests

- How does it work when we move columns/rows if some of them are hidden
- How does it work when we insert or remove new columns/rows
- How does it work with copy & paste, and `skipHiddenRows`, `skipHiddenColumns` settings
- Does it `exportFile` correctly?
- Does `hiddenColumns` and `collapsibleColumns` work together correctly?
- Does `hiddenRows` work correctly with `trimRows`, `filters`, and `nestedRows`
- Are all `d.ts` definitions adjusted
- `hiddenColumns` should work with `stretchH`
- `hiddenColumns` should work with `manualColumnResize`

**Comment by AMBudnik** [comment]
Closed with the release of v8.0.0
