### ISSUE TITLE
Add modifySourceData hook and setSourceDataAtRowProp, setSourceDataAtCell methods

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6664]
### Description

We need a hook that is similar to our `modifyData` hook. But this one should be called each time the source data is requested. Use cases are around formula plugin atm. Part of #6466.

### Tasks

- [ ] Add `modifySourceData` hook to `getSourceData`, `getSourceDataArray`, `getSourceDataAtCell`, `getSourceDataAtCol`, `getSourceDataAtRow` methods.
- [ ] `modifySourceData` hook should have the same syntax as `modifyData` hooks: `modifyData(row, column, valueHolder, ioMode)`.
- [ ] `modifySourceData` hook should support both `ioMode`s: `set` and `get`.
- [ ] `modifySourceData` can return modified source, so the reference is broken. Therefore:
    - [ ] We have to introduce `setSourceDataAtRowProp` and `setSourceDataAtCell`. With the same syntax as `setDataAtRowProp` and `setDataAtCell`. Without adding new hooks (`afterSetDataAtCell`, `afterSetDataAtRowProp`).
    - [ ] Refeactor plugins that were using `sourceData` as a reference: `nestedRows`, `observeChanges`, `undoRedo`
- [ ] I think those two issue will be solved as well:
    - [ ] #6548 `getByRange` for sourceData doesn't work properly with nested object data. 
    - [ ] #3959 DataSource.getByRange (toArray = true) doesn't work for nested objects. 

### Syntax for  `setSourceDataAtRowProp` and `setSourceDataAtCell`

```ts
setSourceDataAtCell(row: number, col: string | number, value: Handsontable.CellValue, source?: string): void;
setSourceDataAtCell(changes: Array<[number, string | number, Handsontable.CellValue]>, source?: string): void;
setSourceDataAtRowProp(row: number, prop: string, value: Handsontable.CellValue, source?: string): void;
setSourceDataAtRowProp(changes: Array<[number, string | number, Handsontable.CellValue]>, source?: string): void;
```

**Comment by wojciechczerniak** [comment]
This is a breaking change and will have to be included in the migration guide @scarletfog

**Comment by aninde** [comment]
Done in https://github.com/handsontable/handsontable/pull/6678.
