### ISSUE TITLE
New modularization approach

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#7381]
### Description
We would like to add some improvements to the following parts of the library:

- [x] should be possible to import only the necessary parts of the library
```
 // load only the necessary code to run core functionalities, without not necessary plugins/cell types/editors/renderers/validators
import Handsontable from 'handsontable/base';
```

- [x] should be possible to import cell types/editors/renderers/validators on demand
```
// import  editor and the interface to registering
import { /* EditorClass */, registerEditor } from 'handsontable/editors';

// import renderer and the interface to registering
import { /* RendererFunc */, registerRenderer } from 'handsontable/renderers';

// import validator and the interface to registering
import { /* ValidatorFunc */, registerValidator } from 'handsontable/validators';

// import cell type and the interface to registering
import { /* CellType */, registerCellType } from 'handsontable/cellTypes';
```

- [x] should be possible to import
```
// import plugin and the interface to registering
import { /* PluginClass*/ , registerPlugin } from 'handsontable/plugins';
```
The order of registering plugins is important 'cause we have to register hooks in proper order. Thus we have to modify the current process of plugin registering to keep current order of pre-built plugins and let end-developers register theirs' custom plugins out of this order.

- [x] should be possible to import Handsontable in a backwards-compatible way
```
import Handsontable from 'handsontable';
```

- [x] should leave UMD's build without any changes for end-developers

**Comment by aninde** [comment]
The tests showed no other bugs. 
You can find the description of the tests [here](https://github.com/handsontable/quality/issues/85#issuecomment-768974154).
