### ISSUE TITLE
Few more examples for our documentation

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#7534]
### Description
We have those already planned for Angular and React. We should add them for Vue as well.

- [ ] Binding settings with an object
- [ ] Binding settings with an attributes
- [ ] Interacting with Handsontable in your app (ie. checkbox, button)
- [ ] Custom validator
- [ ] Custom cell type
- [ ] Declarative `hot-column` definition (+ `v-for` version) + describe what happens:
  - [ ] when both `<hot-column>` and `<hot-table columns="[ ... ]">` are defined 
  - [ ] when where `<hot-column>` slot has more than one/two/supported components
  - [ ] when `<hot-column renderer="CutomRender">` and `<hot-column></hot-renderer is="CustomRenderer"></hot-column>` are both defined. Same for editor.
- [ ] `hot-renderer` example with custom Vue component how-to
- [ ] `hot-editor` example with custom Vue component how-to
- [ ] Update `@handsontable/vue` in all our examples
- [ ] How to use Vue Handsontable without webpack: https://github.com/handsontable/vue-handsontable-official/issues/107
- [ ] Languages example works only for the UMD? For Webpack build languages should be registered first?
- [ ] Example about data mutability handsontable/vue-handsontable-official#103 handsontable/vue-handsontable-official#123
- [ ] Creating a Higher Order Component handsontable/vue-handsontable-official#135

**Comment by KrzysztofZie** [comment]
Please check the latest documentation. 
https://handsontable.com/docs/angular-data-grid/vue3-installation/
https://handsontable.com/docs/angular-data-grid/

If you need anything, please start a new thread.
