### ISSUE TITLE
Migration to TS

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#8144]
### Description
This is an epic to group issues and tasks for migrating source code to TS.

### What we have to do
- [ ] prepare an initial PR with all necessary changes in toolchain and building process with as minimal interference as possible to the daily work
- [ ] migrate 318 files gradually, where we had to add `// @ts-nocheck`
- [ ] improve linter configuration for `src` and `test` files
- [ ] replace hand-made definition file with code-based one
- [ ] consider replacing `jsdoc` with `tsdoc` - and accordingly adjust documentation generating

### Related tasks
- [ ] #7317 Improve definitions for `CellCoords` and `CellRenge`
- [ ] #7489 The Handsontable modules do not support TypeScript
- [ ] #7499 copyPasteEnabled property is missing from hiddenColumns.Settings typings
