### ISSUE TITLE
Add missing describing the test environment settings.

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8491]
**Context**
WIP

**Description**
Added describing the test environment settings so the user will know what to set up to make the tests pass. We do not want our users to waste time debugging unnecessarily.
Changes related to environment settings are published on [PR # 71](https://github.com/handsontable/docs/pull/71)

**Task to be done**
- [x] Add `Environments settings`.
- [ ] Add separated list of `How to ...?` with description of Jasmine's GET parameters like `spec`, `seed`, `failFast`, `random` and `throwFailures`.
- [ ] Add to `How to ...?` description of false-positive failures.
- [ ] Add to `How to ...?` description of settings for how running tests in correct order.

**Comment by AMBudnik** [comment]
Current testing guide: https://handsontable.com/docs/testing/#testing-with-npm-cli
Checkbox #1 after merging the PR https://github.com/handsontable/docs/pull/71 is achieved.
