### ISSUE TITLE
[HyperFormula] New formula plugin II

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#8511]
### Description

Epic. Continuation of handsontable/handsontable#6466

We've went far, but there are few more things to finish. Building on a solid foundation of v9.0.0, were going to extend the functionality of FormulaPlugin and integrate it even more with core Handsontable funtionalities.

- [ ] Blocker: Move Handsontable to its own NPM workspace
- [x] Update HF: handsontable/handsontable#8502
  - [x] Should fix: handsontable/handsontable#8104
  - [x] Should fix: handsontable/handsontable#8057
- [ ] Rethink renderable/logical/physical indexes support
  - [ ] Rethink `modifySourceData`, `beforeChange`, `beforeAutofill` data flow handsontable/handsontable#8130 
  - [ ] Use new HF 1.0.0 methods:
     - [x] Should fix: handsontable/handsontable#6932 
     - [ ] Should fix: handsontable/handsontable#8238
     - [x] Should fix: handsontable/handsontable#8107
     - [ ] Should fix: handsontable/handsontable#8114
  - [ ] Support hidden rows/columns
  - [ ] Support sorting
  - [ ] Support filtering
  - [ ] Support manual move 
  - [ ] Support merge cells
- [ ] Batching support: handsontable/dev-handsontable#394
- [ ] Clipboard support: handsontable/handsontable#6767
- [ ] Autofill support: handsontable/dev-handsontable#384
- [ ] Support undo/redo:
  - [x] Should fix: handsontable/handsontable#8078
- [ ] Fix linked instances: handsontable/dev-handsontable#393
  - [ ] Should fix: handsontable/handsontable#8391
- [ ] Formula debugging: handsontable/dev-handsontable#392
- [ ] A1 helpers: handsontable/dev-handsontable#391
- [ ] Formulas helpers: handsontable/dev-handsontable#388
- [ ] Custom languages: handsontable/dev-handsontable#390
- [ ] Custom functions: handsontable/dev-handsontable#389
- [ ] Show formulas:  handsontable/dev-handsontable#387
- [ ] Named expressions support: handsontable/dev-handsontable#386
- [ ] Support search plugin
- [ ] Support summary calculation plugin
- [ ] Support export to file plugin
- [ ] Support tracing data types and setting correct editor and renderer with `getCellValueDetailedType`
  - [ ] Should fix handsontable/handsontable#8794
- [ ] Add formula cell details to cell meta: handsontable/dev-handsontable#385

### Links

API definitions are here: handsontable/handsontable#7663

**Comment by swistach** [comment]
I'm not sure if it: https://forum.handsontable.com/t/hyperformula-license-key-is-missing/5379 fits that epic, but showing a warning of missing licence key would be a nice fix.

**Comment by AMBudnik** [comment]
Self note - update [forum](https://forum.handsontable.com/t/auto-update-formula-after-row-column-is-moved/5500)
