### ISSUE TITLE
[HyperFormula] Add formula details to cell meta

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#8512]
### Description

HyperFormula stores lots of cell detailed information. We may get it with `getCellFormula`, `getCellType`, `getCellValueDetailedType`, `getCellValueFormat`, `getCellValueType`, `isCellPartOfArray`. With additional information about the cell developers will be able to customize renderer to show error indicator in the corner and/or additional error message as a tooltip:

![obraz](https://user-images.githubusercontent.com/4718998/125847929-2496bad1-cda7-4707-bb2f-d252fbcb7769.png)

We may add is as a feature as well.

### To do

- [ ] Add `formula` to cell meta with formula string
- [ ] Add `formulError` to cell meta with detailed error message
- [ ] Add `valueFormat` to cell meta with tracked format
- [ ] Add `valueType` to cell meta indicating formula data type tracking
- [ ] Other?
- [ ] Document the feature
