### ISSUE TITLE
[GUIDE] How to test Handsontable in your app

### ISSUE THREAD

**Issue by scarletfog** [handsontable/handsontable#8582]
### Description

We need a new guide/section on how to test Handsontable as a part/component of the user app.
- [ ] How to add IDs to context menu https://github.com/handsontable/handsontable/issues/5770
- [ ] How to add IDs to cell https://github.com/handsontable/handsontable/issues/6570
- [ ] How to change data https://github.com/handsontable/handsontable/issues/6570
