### ISSUE TITLE
[RTL] Overview

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#8760]
# Intent

This topic assumes to implement and made adjustments to Handsontable to make it compatible with RTL languages. In the right-to-left texts, writing starts from the right side and goes to the left. It is commonly in use for Arabic, Hebrew, Persian, and some other languages.

Implementing RTL touches every single element of UI. I split the process into categories and smaller topics, which will be discussed and getting done separately.

I intend to cover whole this feature by tests. As the RTL mode does not change the dom, it requires to use of visual testing.

### Walkontable

The `walkontable` is an internal module in charge of drawing the data grid. In the scope of RTL it requires adjustments:

* Overlays:
  * [x] #8761
  * [x] #8762
  * [x] #8763 
  * [x] #8764 
  * [x] #8765
  * [x] #9094
* Renderes: **Edit:**  No founded code relating to the RTL
  * [x] cells
  * [x] colGroup
  * [x] columnHeaders
  * [x] rowHeaders
  * [x] rows
  * [x] table
* Misc:
  * [x] Scroll - should be always on the right of the table.
  * [x] Borders and padding:
    * [x] #8767
    * [x] #8769
    * [x] #8785
    * [x] #9129
  * [x] Sellection
    * [x] https://github.com/handsontable/handsontable/issues/8768
  * [x] https://github.com/handsontable/handsontable/issues/9106 
  * [x] https://github.com/handsontable/handsontable/issues/9107
  * [x] #8910
  * [x] #8911
  * [x] #9113 
  * [x] #9130

* Possible difficulties and recommendations:
  * Issues with size calculations (cell/col/row/table/viewport sizes) for RTL languages: cover that cases by visual tests.
  * The naming constains `Left` which has different associations for RTL and LTR languages: Rename `Left` to `Start`, which is a logical proper term.

### CellTypes

Cell types are a basic feature of Handsontable. Each has its own validator, renderer, and editor.
  * [x] #8795
  * [x] #8797
  * [x] #8800
  * [x] #8802
  * [x] #8803
  * [x] #8791
  * [x] passwordType
  * [x] textType
  * [x] #8805

Possible difficulties and recommendations:
  * Cursor for editors has incorrect behavior: to fix and cover by visual tests. 
    * [x] #8792 

### Plugins

The Handsontable has implemented a plugin system. The default build is a set of plugins included. To realize RTL, it is required to implement it to each official plugin. Additionally, a plugin might be created and maintained by a community or internal customer dev team. We are responsible for describing in detail how to do add RTL support to plugins.

Plugins possibly in relation to RTL: 
  * [x] autoColumnSize
  * [x] #8809
  * [x] #8812
  * [x] #8813
  * [x] columnSummary
  * [x] #8822
  * [x] #8825
  * [x] copyPaste
  * [x] https://github.com/handsontable/handsontable/issues/8785
  * [x] #8826
  * [x] #9186
  * [x] exportFile
  * [x] #8828
  * [x] #8829
  * [x] #8832
  * [x] #8833
  * [x] #8835
  * [x] manualRowMove
  * [x] https://github.com/handsontable/handsontable/issues/9177
  * [x] mergeCells
  * [x] https://github.com/handsontable/handsontable/issues/9124
  * [x] nestedHeaders
  * [x] #8836
  * [x] search
  * [x] trimRows
  * [x] formulas
  * [x] #9178
I am unabled to check:
  * [x] #8855
  * [x] touchScroll 
  * [x] dragToScroll

Possible difficulties and recommendations:
  * Potentially many not visible issues for initial research: Update this topic each time, when the issue was found.

### Configuration and control

* [x] #9132
* [ ] Adapt official demo to work with RTL: https://handsontable.com/demo

## References:
* Issue https://github.com/handsontable/handsontable/issues/83
* Project https://github.com/handsontable/handsontable/projects/14
* https://www.w3.org/International/questions/qa-html-dir
* Handsontable's knowledge base.

## Summary

Implementing RTL will touch a lot of single topics which I listed above. Discussing all of these things here in one topic will make chaos. I'm creating separate tasks for each of these things, and I invite you to discuss and correct me every then when I'm wrong.

Regards!

**Comment by aninde** [comment]
I checked the display of Handosntable in different configurations placed in div with the dir = "rtl" attribute on the following devices. I did not find any errors other than those already reported and described.

Device list
| Device | OS | Browsers (LTS version matched to OS) |
| ----------- | ----------- | ----------- | 
| iPhone 6S | iOS  14.8 | Safari, Chrome | 
| iPhone SE (2020) | iOS 15.1 | Safari, Chrome | 
| Xiaomi Mi A2 Lite | Android 9 | Chrome, Firefox | 
| Samsung Galaxy A51 | Android 11 | Chrome, Samsung Internet, Firefox | 
| iPad (6th generation) | iPadOS 14.0 & 15.1 | Safari, Chrome |

**Comment by Siemienik** [comment]
@aninde Thank you for your effort 👍

**Comment by AMBudnik** [comment]
Note to myself (inform https://handsontable.zendesk.com/agent/tickets/27857)

**Comment by aninde** [comment]
Tested during code freeze of v12.0.0. Works as excepted.

**Comment by AMBudnik** [comment]
This functionality is added to Handsontable v12.

Here https://handsontable.com/docs/layout-direction/ we describe how to set up the RTL support.

If you have any questions about the functionality or need help with the configuration please contact us at support@handsontable.com
