### ISSUE TITLE
EPIC: Modularization for wrappers

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8816]
### Description

The issue is about adding the modularization support to our wrappers. The [modularization](https://github.com/handsontable/handsontable/issues/7381) is available for the vanilla js since [Handsontable v8.3.0](https://github.com/handsontable/handsontable/releases/tag/8.3.0) and it would be great to make it the same for them.

The wrappers that need to be adjusted to support the feature:
- [x] https://github.com/handsontable/handsontable/issues/8818;
- [x] https://github.com/handsontable/handsontable/issues/8819;
- [x] https://github.com/handsontable/handsontable/issues/8820;
- [x] #7489

### Your environment
* Handsontable version: -
* Browser Name and version: -
* Operating System: -

**Comment by AMBudnik** [comment]
This epic can be closed as done. Modularization was added to Handsontable v11.

For everyone interested in the subject, here are the corresponding tutorials
- Angular - https://handsontable.com/docs/angular-modules/ 
- Vue - https://handsontable.com/docs/vue-modules/
- React - https://handsontable.com/docs/react-modules/

And here is the migration guide from v10 to v11 https://handsontable.com/docs/migration-from-10.0-to-11.0/
