### ISSUE TITLE
Grouped issues for missing, misleading or insufficient documentation for `options`

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9331]
### Description

Below is the list of [options](https://handsontable.com/docs/api/options/) that are should be provided with a better description in the documentation. 
Options contain the table which indicates if a change of the value for a given option on the other level of the implementation changes the outcome.

Those levels are
* table (main setup object)
* [`columns`](https://handsontable.com/docs/api/options/#columns)
* [`cells`](https://handsontable.com/docs/api/options/#cells)
* [`cell`](https://handsontable.com/docs/api/options/#cell)

### Why it is important
In Hansontable we allow developers to use cascading settings. This way for example if you set up the a global `readOnly` mode you are able to exclude a single range of cells from the equation.
![Zrzut ekranu 2022-03-21 o 14 28 53](https://user-images.githubusercontent.com/10757813/159270952-4abead9b-0957-4ee2-b464-9ff515e3ddcc.png)
_(demo https://jsfiddle.net/dt0ukob8/2/)_
However, not all of the options can be used on all of the levels. Here in this issue, we've gathered some ideas on how to alter the option descriptions to reflect the actual state of the options.

### List
- [ ] [`activeHeaderClassName`](https://handsontable.com/docs/api/options/#activeheaderclassname) - It's not clear if the table level is the only one where this option works. It would make sense to be used on the `columns` level.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`allowEmpty`](https://handsontable.com/docs/api/options/#allowempty) - Works on all of the levels. Documentation suggested that it is dedicated to `table` and `columns`.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [x] </li>      |    <ul><li>- [x] </li>     |    <ul><li>- [x] </li>    |

- [ ] [`allowInsertColumn`](https://handsontable.com/docs/api/options/#allowinsertcolumn) - We should add the information that it works **only** on the top level. We may also add a link to a demo that shows how to create a custom context menu option with `disabled` settings on a given level.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`allowRemoveColumn`](https://handsontable.com/docs/api/options/#allowremovecolumn) - We should add the information that it works only on the top level. We may also add a link to a demo that shows how to create a custom context menu option with `disabled` settings on a given level.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`bindRowsWithHeaders`](https://handsontable.com/docs/api/options/#bindrowswithheaders) - Documentation isn't clear enough about what this option is exactly for. 

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`checkedTemplate`](https://handsontable.com/docs/api/options/#checkedtemplate) - We should mention then `true` is no longer a valid option if we set up a custom `checkedTemplate`. Demo for tests https://jsfiddle.net/9vufLag5/5/ 

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [x] </li>      |    <ul><li>- [x] </li>     |    <ul><li>- [x] </li>    |

- [ ] [`collapsibleColumns`](https://handsontable.com/docs/api/options/#collapsiblecolumns) 
    - [ ] We should add a graphic that shows how we count the levels
    - [ ] Reference to a related issue https://github.com/handsontable/handsontable/issues/8451
    - [ ] Demo at https://handsontable.com/docs/api/collapsible-columns/#description with `nestedHeaders: true` does not make sense for developers as it does not show any headers https://jsfiddle.net/9vufLag5/6/

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`data`](https://handsontable.com/docs/api/options/#data) - different use than data on the table level https://github.com/handsontable/handsontable/issues/8464, referenced issue https://github.com/handsontable/handsontable/issues/8588

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [x] different `data` </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`defaultDate`](https://handsontable.com/docs/api/options/#defaultdate) - Docs https://handsontable.com/docs/api/options/#defaultdate does not tell truth. The `defaultDate` is used in the cell editor - date picker. It is not added to the empty cell by default.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [x] </li>      |    <ul><li>- [x] </li>     |    <ul><li>- [x] </li>    |

- [ ] [`disableVisualSelection`](https://handsontable.com/docs/api/options/#disablevisualselection) - a few weeks back we thought that it should work only for table level. But here https://github.com/handsontable/handsontable/issues/5082 we wanted to make it work for all of the layers. We should specify where it can be declared.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`dropdownMenu`](https://handsontable.com/docs/api/options/#dropdownmenu) - many users ask to be able to remove the dropdown menu icon for some of the columns - we should mention that it is a table (top) option only.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`fixedRowsBottom`](https://handsontable.com/docs/api/options/#fixedrowsbottom) - Information about 'height' property being obligatory is missing form docs. If the table does not use the parent container in height it does not add scroll and does not add fixed area.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`fixedRowsTop`](https://handsontable.com/docs/api/options/#fixedrowstop) - Information about 'height' property being obligatory is missing form docs. If the table does not use the parent container in height it does not add scroll and does not add fixed area.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`isEmptyCol`](https://handsontable.com/docs/api/options/#isemptycol) - how does it work? It does not seem to do anything https://jsfiddle.net/75q3Lhje/3/

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    ?  |     ?      |    ?    |    ?   |

- [ ] [`isEmptyRow`](https://handsontable.com/docs/api/options/#isemptyrow) - how does it work? It does not seem to do anything https://jsfiddle.net/75q3Lhje/5/

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    ?  |     ?      |    ?    |    ?   |

- [ ] [`language`](https://handsontable.com/docs/api/options/#language) - we should add at least one sentence what this option does in the /options

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`mergeCells`](https://handsontable.com/docs/api/options/#mergecells) - More a question: is there a way to merge cells in `cells`?

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`nestedHeaders`](https://handsontable.com/docs/api/options/#nestedheaders) - it's worth saying that `label` used within `columns` is replaced with `label` from `nestedHeaders` https://jsfiddle.net/8jgzeq1t/8/

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`observeDOMVisibility`](https://handsontable.com/docs/api/options/#observedomvisibility) - how does it work? https://jsfiddle.net/L32qh0of/2/ It is not well explained.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`preventOverflow`](https://handsontable.com/docs/api/options/#preventoverflow) - we should add some graphics or links. Users may be confused about what this option does.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`preventWheel`](https://github.com/handsontable/handsontable/blob/2dbc605c14b4f13eb25b77679f1c1cab98a274ad/handsontable/types/settings.d.ts#L174) - It is not in the docs at all - what does it do?

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    ?  |     ?      |    ?    |    ?   |

- [ ] [`startCols`](https://handsontable.com/docs/api/options/#startcols) - it is said that it works only on the instance level and that is true. But maybe we could add that those rows are counted as `minSpareCols` when we add that option https://jsfiddle.net/ern9ts67/2/

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`startRows`](https://handsontable.com/docs/api/options/#startrows) - it is said that it works only on the instance level and that is true. But maybe we could add that those rows are counted as `minSpareRows` when we add that option https://jsfiddle.net/ern9ts67/2/

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`strict`](https://handsontable.com/docs/api/options/#strict) - it the docs it looks like it should work only on the `columns` level but it works well on all of the levels https://jsfiddle.net/zkgaqp8r/2/

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [x] </li>      |    <ul><li>- [x] </li>     |    <ul><li>- [x] </li>    |

- [ ] [`trimDropdown`](https://handsontable.com/docs/api/options/#trimdropdown) - it's not clear what this option does. We may add two images for the `true`/`false` comparison and it is a UI change.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [x] </li>      |    <ul><li>- [x] </li>     |    <ul><li>- [x] </li>    |

- [ ] [`uncheckedTemplate`](https://handsontable.com/docs/api/options/#uncheckedtemplate) - We should mention then `false` is no longer a valid option if we set up a custom `uncheckedTemplate`. Demo for tests https://jsfiddle.net/fvq4ej7s/2/. We should add more examples as it works well on all of the levels

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [x] </li>      |    <ul><li>- [x] </li>     |    <ul><li>- [x] </li>    |

- [ ] [`validator`](https://handsontable.com/docs/api/options/#validator) - we specify that it works for all of the levels. Now we have 3 examples for `columns` https://handsontable.com/docs/api/options/#validator

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [x] </li>      |    <ul><li>- [x] </li>     |    <ul><li>- [x] </li>    |

- [ ] [`visibleRows`](https://handsontable.com/docs/api/options/#visiblerows) - It is not clear in the docs that this options work on each level, and it works well. We should add info that if `height` is set for the table then the list of choices visibility may change. Open `B4` dropdown to see 3 options instead of 4 https://jsfiddle.net/u4r1g3k9/26/ 

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [x] </li>      |    <ul><li>- [x] </li>     |    <ul><li>- [x] </li>    |

- [ ] [`width`](https://handsontable.com/docs/api/options/#width) - "`width` itself does not work if added to the table, you need to specify `height` in the configuration object - this is not mentioned in the docs https://handsontable.com/docs/api/options/#width
Settings up `height` via CSS inline in the DIV does not work, the `height` has to be defined via configuration object.

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [ ] </li>      |    <ul><li>- [ ] </li>     |    <ul><li>- [ ] </li>    |

- [ ] [`wordWrap`](https://handsontable.com/docs/api/options/#wordwrap) - description in the docs mentions only`columns` https://handsontable.com/docs/api/options/#wordwrap. Be sure to mention that it is important if the string contains spaces or not - white spaces https://github.com/handsontable/handsontable/blob/2dbc605c14b4f13eb25b77679f1c1cab98a274ad/handsontable/src/renderers/textRenderer/__tests__/textRenderer.unit.js#L71

| table | `columns` | `cells` | `cell` |
|-------|-----------|---------|--------|
|    <ul><li>- [x] </li>   |     <ul><li>- [x] </li>      |    <ul><li>- [x] </li>     |    <ul><li>- [x] </li>    |

**Comment by kirszenbaum** [comment]
These issues are related (it'd be best to solve them together):
https://github.com/handsontable/handsontable/issues/8431
https://github.com/handsontable/handsontable/issues/8476
https://github.com/handsontable/handsontable/issues/8478
https://github.com/handsontable/handsontable/issues/6833
https://github.com/handsontable/handsontable/issues/9331

**Comment by krzysztofspilka** [comment]
@kirszenbaum 
Before moving on with this task I would a) discuss `data` with @warpech and b) ask @aninde to validate the undefined items above (those with question marks)

**Comment by aninde** [comment]
My part is done.
